### ISSUE TITLE
treat "isolated view" as a regular filter option

### ISSUE THREAD

**Issue by ivanhofer** [opral/monorepo#1127]
![image](https://github.com/inlang/inlang/assets/21335119/6f5a939d-2ed8-43c3-978b-a3df8dedb445)

We kind of render two filter states in the UI. The "Isolated view" state is rendered different than any other filter.
In my opinion, this should be treated like any other filter and it should be rendered after the "Language" filter on the same line.

**Comment by NilsJacobsen** [comment]
@inlang/editor

**Comment by felixhaeberle** [comment]
although this button looks nice, the proposal makes sense 😄

**Comment by NiklasBuchfink** [comment]
I agree, we will find a suitable place for it in the filter row 👍

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Maybe also related #1380

**Comment by NiklasBuchfink** [comment]
@felixhaeberle It's unrelated
This is about how we display this filter state to the user and that it should be part of our filter section.

The mentioned issue is about reacting to all filtering options (lint, language, id, search) with our lintSummary calculation. We removed this feature, as it resulted in lags.
