### ISSUE TITLE
`inlang module build` should fail if node (or other non-browser) APIs are used

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1531]
## Problem 

Critical bugs occur in production like https://github.com/inlang/monorepo/issues/1530 because `inlang module build` is not failing when node (or other non-browser) APIs are used. 

## Proposal 

Validate during the build step that no non-browser APIs are used. 

### How

Add an esbuild plugin to the `inlang module build` command that throws if node imports are encountered. 

https://github.com/inlang/monorepo/blob/d7710fcf2427aad5f53125f7f52375fa468e91e9/inlang/source-code/cli/src/commands/module/build/command.ts#L28-L41

## Additional information

- node APIs can still be be polyfilled. validation ensures that they are actually polyfilled (the reason why https://github.com/inlang/monorepo/issues/1530 was caused)
- polyfilling by default (what we used to do) is setting up the ecosystem to be non-web compliant aka a no-go

**Comment by felixhaeberle** [comment]
@samuelstroschein What's the specific task here? How would you implement this?

**Comment by samuelstroschein** [comment]
@felixhaeberle an esbuild plugin that is embedded in the inlang module build command

**Comment by b4s36t4** [comment]
> polyfilling by default (what we used to do) is setting up the ecosystem to be non-web compliant aka a no-go

@samuelstroschein this means you don't want the build step to be having default polyfills?

**Comment by samuelstroschein** [comment]
> @b4s36t4 this means you don't want the build step to be having default polyfills?

Correct. no polyfills. throw an error to inform the developer to get rid of the node apis or polyfill them themselves

**Comment by A-N-uraag** [comment]
Hi @samuelstroschein, I think I understand the requirement and how to add the new esbuild plugin. I am new to the project and it looks interesting. Can I give it a shot as my first contribution? Thanks!

**Comment by samuelstroschein** [comment]
Hey @Divy0007, @b4s36t4 and @A-N-uraag, 

I was not aware that I need to assign someone. Given that @Divy0007 was first, I would assign him. @Divy0007 do you want to be assigned?

**Comment by b4s36t4** [comment]
@samuelstroschein You really don't need to assign, I would suggest let it open for everyone. Since this is a bit complex (bundling related, esbuild API) making it open for everyone would allow people to provide their own solutions, you could simply select anyone of the raised PR which does satisfy your needs.

**Comment by Divy0007** [comment]
@b4s36t4 is right !!

**Comment by Divy0007** [comment]
Great @Min2who !!

**Comment by Min2who** [comment]
@samuelstroschein can you review my pr

**Comment by b4s36t4** [comment]
Yes, because the of the issue it seems fair to allow multiple people. 

I feel open-source is more of a experience thing rather than money.

**Comment by samuelstroschein** [comment]
@b4s36t4 thanks for the reply. 

@felixhaeberle shall we change the flow to the default everyone can submit a PR?

**Comment by felixhaeberle** [comment]
@samuelstroschein if they prefer, yes. I didn't find the option in the settings tho

**Comment by Divy0007** [comment]
Hey @samuelstroschein  , it seems the solution was provided first by @Min2who  , so kindly process the payment to them. Your humble nature is appreciated! In the future, if you encounter any priority issues, feel free to assign them to me; I'd be glad to help.

Regarding payment to @Min2who , you can use the /tip function via Algora flow. I've attached some links for your reference. Additionally, I contribute to cal.com, where they also facilitate payments through /tip, which can be detected by the Algora bot. Here are some useful links for understanding Algora payments.

https://docs.algora.io/bounties/payments

**Comment by samuelstroschein** [comment]
@A-N-uraag that is a good remark. I fear that a whitelist approach requires us to constantly update the whitelist as more APIs become available. The urge to import cloudflare worker apis is much lower than node's apis. hence, i think the blacklist node api's approach is sufficient for now. 

thanks for raising the issue!

**Comment by felixhaeberle** [comment]
@samuelstroschein How are we going to proceed here? Which approach do you want to take?

**Comment by samuelstroschein** [comment]
@felixhaeberle this is just a backlog issue. i would go for a blacklist approach

**Comment by samuelstroschein** [comment]
closing as stale
