### ISSUE TITLE
[bug] add langugage button is disabled if the user is not logged in

### ISSUE THREAD

**Issue by jannesblobel** [opral/monorepo#1561]
### Problem

The button 'add language' to a project is disabled when a user isn't logged in.
I wasn't logged in, and my first thought was: "This feature is not available. yet"  
![CleanShot 2023-11-01 at 00 05 35@2x](https://github.com/inlang/monorepo/assets/72493222/c75afc56-d7bd-4dc8-b18e-3e83d95b1745)

### Expected behavior

The button 'add language' should be enabled but when the user is clicking on it, a message should displayed like" if you want to contribute another language, please log in via GitHub first"

### Reproduction

1. open a new incognito window
2. go to `https://inlang.com/editor/github.com/inlang/example`
3. try to add a new language without login in

**Comment by NiklasBuchfink** [comment]
> [...] a message should displayed like" if you want to contribute another language, please log in via GitHub first"

Better UX, I will implement it 👍

**Comment by felixhaeberle** [comment]
Is this relevant to our growth efforts?

**Comment by jannesblobel** [comment]
It could. If I want to contribute a new language to cal.com, but it is not apparent via the editor, I wouldn't.
