### ISSUE TITLE
[bug] Web editor doesn't check if the repo is already forked and does not handle out of sync forks

### ISSUE THREAD

**Issue by WarningImHack3r** [opral/monorepo#1614]
### Problem

Pretty self-explanatory: the "no access to this repo, fork it!" floating button doesn't check if the repo is already forked.
It still manages to redirect to the fork but if the fork is too old it might lack the new `project.inlang.json` config and thus lead to an error.

### Expected behavior

An info/warning/error to happen, or even better, suggest updating the fork if it has no commits ahead (else, error).

### Reproduction

1. Have a(n old) fork of a repo using Inlang you don't have access to
2. Press the fork button
3. Notice a bug might happen depending on how old is your fork

**Comment by samuelstroschein** [comment]
@WarningImHack3r Oh I see what you mean now. The editor has no "this does not need to be translated in language X" feature yet. 

Generally, text should not be hardcoded. Twitter might have a different brand name in another language. Hence, the "someone needs to flag this as does not need to be translated" feature :)

**Comment by NiklasBuchfink** [comment]
I'm gonna improve this next week:
- [ ] prompt user with a "warning" that the fork is outdated
- [ ] give users an option to sync forks using GitHub CLI command

cc @janfjohannes

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Status?

**Comment by NiklasBuchfink** [comment]
Not done yet, because of other severe issues in Fink. I will only work on Fink bugs next week.

**Comment by NiklasBuchfink** [comment]
**Short update**

I synced with @janfjohannes about this. He will extend the lix API with two new functions:
- `forkStatus` with commits ahead and behind
- `syncFork` like the one in GitHub

After this has been added, I will implement it in Fink

**Comment by NiklasBuchfink** [comment]
@WarningImHack3r With the merge of https://github.com/opral/monorepo/pull/1983 this feature is now available in Fink ✅
