### ISSUE TITLE
[refactor] remove node polyfills

### ISSUE THREAD

**Issue by janfjohannes** [opral/monorepo#1622]

**Comment by janfjohannes** [comment]
finish the polyfill removal of iso git, this makes only sense if we fork and modernize iso git a bit and also means we should be aligned on strategy how important iso git will be mid to long term for us

the mein issue is the buffer polyfil in internals of iso git and replacing all process usage.

**Comment by samuelstroschein** [comment]
closing because not relevant anymore with lix on sqlite https://opral.substack.com/p/accelerate-by-years-part-iii-lix
