### ISSUE TITLE
lix fs api and fs adapter architecture

### ISSUE THREAD

**Issue by janfjohannes** [opral/monorepo#1633]
see https://docs.google.com/document/d/12mVHd1lZSrd6hpKKKELWqFqREt8IwklqU_AMW46HTKw/edit#heading=h.koppz5wk5t5o

**Comment by felixhaeberle** [comment]
@samuelstroschein @janfjohannes What's the status on this?

**Comment by janfjohannes** [comment]
@felixhaeberle  i handle this as a background task, and only continue here if i have idle time, the main focus is getting lazy loading done, after that this will be prio

**Comment by samuelstroschein** [comment]
Glob support would be awesome. But is likely not important for 1.0

An example use case is here https://github.com/inlang/monorepo/issues/1814#issuecomment-1839225984

**Comment by samuelstroschein** [comment]
duplicate in linear https://linear.app/opral/issue/LIX-4/lix-fs-api-and-fs-adapter-architecture
