### ISSUE TITLE
Publish VSCode extension to OVSX

### ISSUE THREAD

**Issue by openscript** [opral/monorepo#1634]
## Problem 

User reports:

> Could you please upload the Inlang VScode extension also to https://open-vsx.org/ (Opensource alternative to Microsoft Marketplace) We're using Gitpod that uses a forked Vscode instance under the hood, and Microsoft forbids to use the MS Marketplace for forked VScode instances....

We had it once in place, but it was not reliable.

## Proposal

- [ ] Make OVSX API key available to CD @samuelstroschein 
- [ ] Enable deployment to OVSX
- [ ] Validate if it works

**Comment by samuelstroschein** [comment]
@felixhaeberle you have access to doppler etc. can you do this?

**Comment by openscript** [comment]
Seems like this is not in doppler, yet?

https://github.com/inlang/monorepo/blob/20cdd53b1efc093c5f715a87a8046583a3e682f6/.github/workflows/publish-ide-extension.yml#L47

**Comment by openscript** [comment]
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by felixhaeberle** [comment]
@samuelstroschein Can you DM me your Eclipse credentials?

**Comment by samuelstroschein** [comment]
@felixhaeberle i can add you as a user. what is your vsx username?

**Comment by felixhaeberle** [comment]
@samuelstroschein as always: felixhaeberle

**Comment by felixhaeberle** [comment]
please add me and re-assign after it's done

**Comment by samuelstroschein** [comment]
@felixhaeberle i added you

**Comment by felixhaeberle** [comment]
We will bring the inlang extension to OVSX with the latest updates in #1879.

**Comment by felixhaeberle** [comment]
@opral/team Published on OVSX https://open-vsx.org/extension/inlang/vs-code-extension 🥳

cc @medihack
