### ISSUE TITLE
move auth callback pages to lix proxy (make lix:dev independent of website for simpler dev(

### ISSUE THREAD

**Issue by janfjohannes** [opral/monorepo#1682]

**Comment by janfjohannes** [comment]
as discussed we move the vike renderer setup and the auth callback page to the server package to be able to strat lix just with the editor. unlike the original plan we will keep the duplicated localstorage providers between editor and website and instead will improve this by removing user from localstorage. @NiklasBuchfink

**Comment by janfjohannes** [comment]
@samuelstroschein  @NiklasBuchfink  now that we found a way to use the auth callback pages across domain origins we can move the auth callback pages from website, fink and manage to lix. only gotacha is that they would all look te same, but as they are not really styled anyways i dont see an issue.

**Comment by samuelstroschein** [comment]
closing as stale / likely has a duplicate in linear
