### ISSUE TITLE
introduce module registry

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1688]
## Problem 

_THis issue should not be confused with a module management app_

1. Constant caching problems with JSDelivr

- #678 
- #1090 

2. Users are confused and think they can install modules via npm 

- #1684 

## Proposal 

Introduce a registry and avoid NPM and JSDelivr.

**Comment by felixhaeberle** [comment]
@samuelstroschein Are you responsible for this task?

**Comment by samuelstroschein** [comment]
No. It's just on the prio list

**Comment by samuelstroschein** [comment]
closing as stale / likely has a duplicate in linear
