### ISSUE TITLE
Add pricing label on apps that will have a internal pricing

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/monorepo#1749]
## Problem 
The products you can find on inlang.com have their own licenses or pricing strategies. Even though a lot of products, especially the dev tools remain free, there will be apps like parrot, that target designers and can have a internal pricing. We need to communicate that. 

## Do it like a app store
![image](https://github.com/inlang/monorepo/assets/58360188/e834647c-0cd5-4277-b624-fd8558e6287d)

In an app store you directly see what apps are free or which ones are paid. 
(Question: How can we show a freemium model in these little badges)

I'm gonna explore that further and keep you updated.

In general, I think it's a good idea to have these elements on the pages to have a very transparent pricing experience for the users.

@inlang/martketplace-infrastructure @martin-lysk @inlang/website 

Left Todos:

- [ ] Add pricing information in markdown
- [ ] Check consistency of labels

**Comment by NiklasBuchfink** [comment]
This is needed and the button indicates it at first sight, but you see it very tiny underneath these buttons. The status quo is "in-app purchases", subscription and freemium models. This should be made very clear on the product pages, but this can't be squeezed into the small preview cards without enforcing specific pricing models.
It could be enough to mark cards with something generic that indicates an app's premium / paid / team / enterprise option. People will get it if the preview card has a "Pro badge" or something and there is a pricing model on the product page.

**Comment by flornkm** [comment]
@NilsJacobsen @NiklasBuchfink I have already discussed something like this with Samuel in Discord for our own products: https://discord.com/channels/897438559458430986/1173655847713374479/1173663293576056852

If I get it right, you're talking **just** about "third-party products" that have their own licensing? I absolutely agree that we need to put pricing information somewhere. On the product pages, I think it makes sense to include it above the license as it is somehow related:

<img width="1396" alt="Screenshot 2023-11-27 at 12 40 54 PM" src="https://github.com/inlang/monorepo/assets/92092993/9d433603-db7d-43c2-9c56-5918f2db3752">

**Comment by NilsJacobsen** [comment]
Let me work on a concept for that today.

**Comment by NilsJacobsen** [comment]
**Update:** 
We will add a customizable label on the cards for more flexibility. Apps will have different pricing approaches, so it will be chaos to put in categories.
The same label will live in the sidebar. The pricing section can be done with a md table. We probably link the pricing label in the sidebar with an anchor to the pricing section.

**Comment by NilsJacobsen** [comment]
**Update:**

last step is to put a pricing statement on the dev tools pages to explain that we don't plan to monetize them.

What do you think about something like that:

```md
## Pricing

Our developer tools are not part of our monetization strategy. We're committed to empowering developers and easing the pain of internationalization (i18n).

### Why?

We believe in supporting developers worldwide without any cost, fostering innovation and collaboration within the community.

### How Do We Sustain?

While our developer tooling is free, we sustain our operations through premium services in our other apps. Your support keeps these tools accessible to all.
```

**Comment by samuelstroschein** [comment]
### Too much marketing blabla. Examples:

> We're committed to empowering developers and easing the pain of internationalization (i18n).

What does empower mean here?

> We believe in supporting developers worldwide without any cost, fostering innovation and collaboration within the community.

Nope. We surely don't believe in supporting devs for free. We get sales and marketing in return. 

---  

### Here is my one-paragraph suggestion:

> Dev tools are free of charge. 
> 
> We subsidize developing and maintaining dev tools to solve i18n and get marketing and sales in return. If we build dev tools that make i18n easy and developers love, more companies will internationalize, and developers will recommend the inlang ecosystem to their employers/companies. 

Why? no fluff. making clear why we subsidize dev tools and what our incentives are. @NilsJacobsen and @jldec (given your gitpod experience) what do you think?

**Comment by NilsJacobsen** [comment]
Well it's pretty blunt, but honest. I like it. 

maybe we can change the second sentence to: "If we create developer tools that simplify i18n and are loved by developers, they will recommend the inlang ecosystem to their employers/companies." I feel it reads a bit easier.

I'm not sure if I would have found the section if it's not called pricing. What do you think?

**Comment by samuelstroschein** [comment]
> "If we create developer tools that simplify i18n and are loved by developers, they will recommend the inlang ecosystem to their employers/companies."

Indeed. Reads better. 

> Dev tools are free of charge.
> 
> We subsidize developing and maintaining dev tools to solve i18n and get marketing and sales in return. If we create developer tools that simplify i18n and are loved by developers, they will recommend the inlang ecosystem to their employers/companies. Other parts of the ecosystem that are important to large companies will be monetized, not the dev tools.

**Comment by samuelstroschein** [comment]
_Actually, why not adding the "business value" sentence? @NilsJacobsen what do you think?_

Dev tools are free of charge.

We subsidize developing and maintaining dev tools to solve i18n and get marketing and sales in return. If we create developer tools that simplify i18n and are loved by developers, they will recommend the inlang ecosystem to their employers/companies. Other parts of the ecosystem that are important to large companies will be monetized. Our incentive ensures recurring investments into the dev tools because they have business value.

**Comment by jldec** [comment]
How about:

> Our developer tools and libraries are free.
> We will charge for other parts of the ecosystem which add value for companies operating internationally. 

(prefer fewer words - would avoid the word "monetize")

**Comment by jldec** [comment]
even simpler maybe

>  Our developer tools and libraries are free.
>  We will charge for value-add services for companies operating internationally.

**Comment by samuelstroschein** [comment]
I like the shorter version, but it hides the fact why we are building dev tools (marketing, sales). 

_What about this one? @NilsJacobsen @jldec _

> Developer tools and libraries are free. 
> 
> We will charge for value-add services in the ecosystem for large companies. If we create dev tools that simplify i18n and are loved by developers, they will recommend the inlang ecosystem to their employers/companies.

**Comment by NilsJacobsen** [comment]
I think the term "value-add services" is not that clear to me.

What about this one? Merged yours.

> Our developer tools and libraries are free.
We will charge for other products, which add value for companies operating internationally. If we create dev tools that simplify i18n and are loved by developers, they will recommend the inlang ecosystem to their employers/companies.

**Comment by samuelstroschein** [comment]
I think I nailed it. Thoughts? 

- removed "value-add" 
- clarified we target large companies for monetization
- dev tools are necessary [that's why we build them] and act as marketing

> Our developer tools and libraries are free.
> 
> We will charge products and services targeting large companies, not dev tools. We see dev tools as a necessity to solve business problems and marketing. If developers love our dev tools, they will recommend the inlang ecosystem to their (large) companies.

**Comment by jldec** [comment]
LGTM

**Comment by NilsJacobsen** [comment]
I think we can close this.

**Comment by NilsJacobsen** [comment]
<img width="1488" alt="image" src="https://github.com/opral/monorepo/assets/58360188/cf3a04f5-234d-4a87-942e-68183f6af739">
