### ISSUE TITLE
[bug]  Fink does not check the permission after a login process 

### ISSUE THREAD

**Issue by jannesblobel** [opral/monorepo#1766]
### Problem

After a login process, Fink does not check the permissions again. This means that if I want to contribute to my own projects, Fink prompts me to fork my own project.

### Expected behavior

I don't need to fork my own project. 

### Reproduction

1. Open https://inlang.com/editor
2. ensure you are logged out 
3. open a project where you have technical permissions to contribute
4. login with your GitHub account 
5. click on Return to the app
6. as you can see in the git flow bar, it says you need to fork the repo
6. 1. try to add a new language ( this should work, but Finks thinks you haven't the correct permissions ( Fork required) 

7. reload the page 
8. you can add a new language and don't have to fork the repo. 

have

### Other information
I have the permission to contribute
![CleanShot 2023-11-28 at 11 03 06@2x](https://github.com/inlang/monorepo/assets/72493222/b0f92efa-f5d6-47c3-b1bc-c132bae5cce1)

Sorry, the loom  is in German and is more about the add language problem, but I believe this is a result of the problem 
https://www.loom.com/share/a8eafe39ab7043ff9f008a67207e799e.

**Comment by NiklasBuchfink** [comment]
@jannesblobel Should be fixed now ✅

**Comment by NiklasBuchfink** [comment]
I think this issue exists again
