### ISSUE TITLE
add forkSync and diffFork feature for fork handling

### ISSUE THREAD

**Issue by janfjohannes** [opral/monorepo#1784]

**Comment by janfjohannes** [comment]
repo.forkStatus(  origin, branch )   > { ahead: 4, behind: 3 }


>> forward to github: optional : repo.syncFork( origin, branch) > github sync logic, if not possible without confilict return {error: 'has_conflicts'}

**Comment by samuelstroschein** [comment]
Cool to see how the requirements slowly form lix!

**Comment by NiklasBuchfink** [comment]
@janfjohannes Can this be closed?
