### ISSUE TITLE
[bug] using base path in sveltekit brakes inlang

### ISSUE THREAD

**Issue by nosovk** [opral/monorepo#1802]
### Problem

If I add base path to svelte config, and try to use inlang, I always redirected to the root of the app. It seems that's base path settings are ignored by inlang.

### Expected behavior

Get links like /base path/de/

### Reproduction

Add base path setting to sveltekit

**Comment by felixhaeberle** [comment]
Assigning @LorisSigrist for further clarification.

**Comment by LorisSigrist** [comment]
@nosovk Is this still the case with the new SvelteKit guide?

**Comment by nosovk** [comment]
You mean this instruction: https://inlang.com/g/2fg8ng94/guide-nilsjacobsen-buildAGlobalSvelteApp

**Comment by LorisSigrist** [comment]
With the release of `@inlang/paraglide-js-adapter-sveltekit`, this issue should be mute, so I'll close it. If the issue persists feel free to reopen
