### ISSUE TITLE
Paraglide Adapter SvelteKit 1.0

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#1809]
This Issue Tracks the Progress on the Paraglide Adapter for SvelteKit.

- [x] Rewrite `href`s on `<a>` tags
- [x] Rewrite `action` attributes on `<form>` tags
- [x] Rewrite `formaction` attributes on `<button>` tags
- [x] Expose custom `goto` function with rewrites
- [x] Support multiple routing Strategies
    - [x] URL Prefix (can be disabled for default locale)
    - [x] Domain Based
    - [x] SearchParam based routing
- [x] Support config to disable rewrites in part of the App
- [x] Decide on how to handle links on Components (expose translatePath if you really need it)
- [ ] ~~Auto-set the `<html lang>` attribute~~ (would need to somehow inject into hooks.server.js, even if it doesn't exist)
- [x] Automatically set the languageTag if appropriate
- [ ] Test Test Test
- [ ] Documentation

**Comment by LorisSigrist** [comment]
Hmm, you could copy-paste the code from the development branch & try it.
I'm not sure if releasing the current version is a good idea, since there are still some rough edges & it's likely that SvelteKit will offer some of the functionality we're providing natively. We're working with the maintainers on that.

**Comment by xmlking** [comment]
thanks a lot @LorisSigrist  love to use this adapter and remove some boilerplate code from repo https://github.com/xmlking/spectacular/tree/main/apps/console
