### ISSUE TITLE
Stack searches are weak funnels

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/monorepo#1811]
## Problem 
https://www.loom.com/share/6e0db5d7459f47e7981df365d865ec93
The page you see when you clicked on a stack at inlang.com is not good enough. I would feel lost.

## Proposal
Add a Stack header with hardcoded features like on other pages. 

Second step: Make the pages crawlable. To get them indexed for i18n for nextjs -> inlang.com/c/nextjs (make stack a category)

@inlang/martketplace-infrastructure

**Comment by LorisSigrist** [comment]
+1 there is room for improvement here.

The headlines being cut off was fixed in #1822
