### ISSUE TITLE
message query APIs must return a promise

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1846]
## Problem 

Message queries are async in reality but sync in our project API. 

Apps are running into bugs because CRUD operations do not "wait" to be resolved. The CLI's machine translate command for example updates messages (a sync operation in the project) and closes the process before the updated messages are written to disk (an async process). 

https://github.com/inlang/monorepo/assets/35429197/5f7f95cc-04c4-4844-b066-b39e10ee6f2f

### Code examples

The code below inserts setTimeouts after bugs have been identified. We should make CRUD operations async and thereby avoid the need to add setTimeouts and decrease the risk for bugs. 

https://github.com/inlang/monorepo/blob/34b29ddc73993b41da8541367a5beb21c0f92482/inlang/source-code/cli/src/commands/lint/index.ts#L39-L46

https://github.com/inlang/monorepo/blob/34b29ddc73993b41da8541367a5beb21c0f92482/inlang/source-code/cli/src/commands/machine/translate.ts#L133-L135

https://github.com/inlang/monorepo/blob/34b29ddc73993b41da8541367a5beb21c0f92482/inlang/source-code/sdk/src/adapter/solidAdapter.test.ts#L306-L307

**Comment by martin-lysk** [comment]
I thought the same when running into the same issue when integrating it into parrot but I would not agree on this anymore. The cause of the problem is that crud is async while they shouldn't be. The debouncing will become obsolete when #1844 is done.

**Comment by samuelstroschein** [comment]
@martin-lysk this is not a debouncing issue. writing to, or reading from disk is an async operation.

future optimizations like lazy fetching messages (files) will also be an async operation. in short, CRUD operations are async no matter how we spin it.

**Comment by felixhaeberle** [comment]
isn't it the same with lint rules? lint rules are sync atm (as long as I remember, didn't look it up rn), but this is unfortunate, because I want to call a DB / API there potentially (like spell-checking).

**Comment by samuelstroschein** [comment]
@felixhaeberle yes, lint rules should be async too. Any query API should be async.
