### ISSUE TITLE
[bug] Lix FS Interface does not support `fs.readdir("...", { recursive: true })`

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#1850]
### Problem

The Lix-FS Interface does not support the recursive option on `readdir`. 

### Expected behavior

`fs.readdir("...", { recursive: true })` should work

### Reproduction

Step 1: Try to use `{ recursive: true }` on `fs.readdir`
Step 2: Get yelled at by TS

**Comment by janfjohannes** [comment]
@LorisSigrist  could you add a short note on the urgency / where this is needed?

**Comment by LorisSigrist** [comment]
In #1849 I was able to do without this, so it's no longer urgent. Right now this is a nice to have for the future.
However, whenever the need comes up to scan a directory recursively, which in the sdk might very well happen, this would be very useful.
