### ISSUE TITLE
[bug] SDK Message-Watcher occasionally returns no messages when spamming save

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#1876]
### Problem

The SDK watcher sometimes triggers the message-changed callback with no messages when save is being spammed on the `messages/en.json` file

### Expected behavior

It always triggers with the actual messages

### Reproduction

Set up a paraglide project with the vite-adapter and then spam save on the message file.

**Comment by samuelstroschein** [comment]
@LorisSigrist you do you expect to work on this issue? Please default assign people to ensure that issues are being resolved

**Comment by NilsJacobsen** [comment]
I think that issue is sdk related. Will assign @jldec.
