### ISSUE TITLE
vs code extension: inlang tab

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#1879]
## Problem 

🎥 LOOM: https://www.loom.com/share/26f31c4b395b497f91cecf4ab157a6eb

Out of various issues, the need arises for an **Inlang Tab** to not limit growth on the vs code extension, namely that the getting started experience is better, growth is faster & the retention is higher. 

---

This proposal solves various issues around #1831, #1832 & will eventually lead to a so-called "config-free" setup which will streamline the setup process of the extension to 0 steps where competitors have multiple (5-10 steps). 

---

Additionally, we are adding: 

- enhanced monorepo support from one vs code window with just 1-click with the "Project View"
- better messages observability with the "Message View"
- cross-selling to Fink (& in the future CLI)
- better module observability
- better error handling (everything in one place, no disturbing notification / popups anymore)
- the ability for a clear getting started wizard in the "Project View" (postponed from this initiative)
- create messages from outside code files through "Message View" (which will eventually lead to a better editing experience)

## Proposal

> rough textual outline how it could turn out

INLANG

**View 1:  Project**           [icon:settings] (expanded)
  | ✅ Project A            [icon:file] (collapsed) (icon:selected)
    | Modules
    | Errors
  | Project B            [icon:file] (unselected) 
   
or     

Button „Create project“ -> small wizard  

**View 2: Messages**  
  | Message 1     [icon:edit] [icon:file] [icon:fink]  
  | Message 2     [icon:edit] [icon:file] [icon:fink]  
  
or  

Openend file has no messages  
Button „Create message“

or

No project found (alternative: do not render when no project selected)

## UI

The UI is rather limited and we will, as always, stick to VS Code defaults as much as possible, so design happens in code with the rough conceptual outline above.

> This is only showcasing some UI as reference. This has nothing to do with the extension.

<img width="329" alt="Bildschirmfoto 2023-12-12 um 17 17 24" src="https://github.com/inlang/monorepo/assets/34959078/a376e800-6192-417b-b88a-17a22c5228cf">

video of inlang tab: https://github.com/inlang/monorepo/assets/34959078/8b14dd83-d804-488c-9278-b618adf15e15

## Task list
- [x] #1832
- [x] #1909
- [x] #1910
- [x] #1911
- [x] #1912
- ... more follows 

@inlang/team feedback welcome ✨

**Comment by samuelstroschein** [comment]
You should likely take the create new project wizard out of the scope of this initiative. 

The getting started will change based on #1844 and the subsequent #1585 from "select a plugin" to "import messages [if desired]". If you add the wizard now, you must update the whole flow in January. Hence, I suggest taking the getting started wizard out of this initiative.

**Comment by felixhaeberle** [comment]
@samuelstroschein Yes, wizard is out-of-scrope for this initiative.
> I just wanted to outline the ability for it here.

**Comment by felixhaeberle** [comment]
progress

<img width="329" alt="Bildschirmfoto 2023-12-18 um 13 16 16" src="https://github.com/inlang/monorepo/assets/34959078/2f8f77ce-9bf5-441e-9031-1f254e119190">

**Comment by flornkm** [comment]
I can't
<img width="128" alt="Screenshot 2023-12-18 at 1 40 44 PM" src="https://github.com/inlang/monorepo/assets/92092993/f2306758-8077-4ac6-8133-2cfe02142bbc">
it!

**Comment by samuelstroschein** [comment]
@felixhaeberle maybe make the icon outlined to match the rest of vscode's icons?

**Comment by felixhaeberle** [comment]
switching projects in the vs code extension - SO EASY NOW 🤯 

+ direct access to your setting file
+ improved error logging (soon)


https://github.com/inlang/monorepo/assets/34959078/fba4e06b-f649-42e0-8b7e-874fbe3ab37f

**Comment by felixhaeberle** [comment]
@opral/team feedback wanted! ✨

**Message View**

<img width="1276" alt="Bildschirmfoto 2024-01-08 um 15 11 28" src="https://github.com/opral/monorepo/assets/34959078/ce4929c1-a952-456b-903d-f266f43ce843">


1. display all messages in sidebar or only those opened in the current file?
2. highlight currently open messages / resort list based on open file?
3. how should messages be presented? should the context tooltip content (image) be in a collapsible panel "inside" the message id (on click)?

<img width="154" alt="Bildschirmfoto 2024-01-08 um 15 16 22" src="https://github.com/opral/monorepo/assets/34959078/1ae20a6a-2cca-471a-83f2-9abaa93aed8a">

curious what you think! 🥸

**Comment by NilsJacobsen** [comment]
> 1.

What about a switch? Idk if showing all cause problems. Same performance difficulties as in the editor.
The ones on the page are more important.

> 2.

Can you try bigger repos as proof of performance? It could be thousands of messages. Without a search, you can't handle that.

> 3. 

I like the collapsable. It's basically what you see in the hover modal right now, right?

**Comment by felixhaeberle** [comment]
1. where would you place this switch and how should it look like. we have the ability to render a button in the area of "MESSAGES" and beneath in the webview above the message table.

2. Sure, will check performance. 

But I guess we do not have performance issues here at least from the UI side because the HTML used is very minimal and above that it only depends on the UI speed of VSCode which we can also lazy-load in a paginated style. Besides that the @opral/sdk speed is a culprit but this is out of reach for the IDE extension implementation and has to be improved there.

3. Yep.

**Comment by flornkm** [comment]
> 1. display all messages in sidebar or only those opened in the current file?

I agree to Nils, but only if it's not that much of an effort. I can think of usecases (e.g. having a lot of messages), where I want to view only those in the current file. On the other hand I feel like if you quickly want to find a specific message and don't know in which file you have it, you would want to see all. 

> 2. highlight currently open messages / resort list based on open file?

Resorting definitely seems to be beneficial. If I think I look at the messages and below that are "not relevant" ones, it would make me very slow in my workflow.

> 3. should the context tooltip content (image) be in a collapsible panel "inside" the message id (on click) in the sidebar?

Yes. What about hovering the messages? Will this still be possible / optional?

I don't know about the performance, but I mean VS Code also has a workplace-wide search function and works without any issues for me. If the extension uses the same API for searching through files, why should it result in performance issues?

**Comment by jannesblobel** [comment]
1. I would only display the messages on the current page. If the user wants to find a specific message, he will use the search anyway
2. I vote for highlighting the focused message. Resorting might be too much movement when clicking from message to message. And it makes sense to display the same order as in the code?!
3. The collapsible panel is in the sidebar, right? Upvote for that :) 


![CleanShot 2024-01-08 at 17 46 29](https://github.com/opral/monorepo/assets/72493222/f9565d78-fe0b-402d-aabf-47c90eac5734)

**Comment by felixhaeberle** [comment]
To sum it up:

1. We need a search.
2. We highlight the messages in the currently open file. 
> To prevent the resorting & new rendering of all nodes, I will simply display them highlighted on top of the regular list as duplicates, of course with another styling (highlighted). 
3. We want a collapsible to see more context of the message like in the context tooltip.

🫡

Will share the outcome of this later today.

**Comment by jannesblobel** [comment]
1. why not the VS search? 
2. wait, highlight messages in the currently open file, but all messages in the project are displayed? Or are only messages in the currently open file displayed?
