### ISSUE TITLE
Programmatic Linting

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#1889]
**7. Feb 2024**

The current propsal is here https://github.com/opral/monorepo/issues/1889#issuecomment-1856065525

---
 ## Problem 

Currently, the Inlang IDE extension will accept Messages & Message-Ids that do not pass linting when extracting messages.

For example, if you have the `valid-js-identifier` lint rule installed, it will still accept invalid JS identifiers (eg `123test`) as messageIDs. 

## Proposal
Attempt to lint any messages before adding them. If they do not pass linting prompt the user to edit them.

**Comment by felixhaeberle** [comment]
@LorisSigrist Interesting proposal. It's a bit tricky because we have lint rules which work even without having a message (missing message), so I guess what you propose is more control on when in the lifecycle of a message the lint rule gets triggered.

This means lifecycle hooks for the extension like: "onCreateMessage", "onUpdateMessage", ... where we only selectively call lints rules.

**Comment by LorisSigrist** [comment]
Hmm. It slipped my mind that not all lint rules could be used for this.

I suppose giving lint rules a way to "signal" how they can be used would be required to make this work. Or just adding extra lifecycle hooks. Either way, it's inevitably going to be an expansion of the API, so we need to be careful. 

That being said, i think this is going to pop up quite often, especially if inlang is being used to manage translation in an OSS project, where the people contributing are unlikely to be familiar with the linting setup. Having a way to prevent mistakes before they happen would be a win. 

We could consider having this be part of the "external" config for lint rules. We already control if they `warn` or `error` from the `project.inlang/settings.json`, maybe we could also flag the ide-behaviour there.

**Comment by felixhaeberle** [comment]
> If you think about it, we just need a more fine-grained version of error vs warn, depending on the environment (cli vs ide)

Can you elaborate?
We currently only control how they are being executed / interpreted, not when.

**Comment by samuelstroschein** [comment]
The solution could be very simple if apps can programmatically lint a message via the SDK: 

```ts
const message = await userInputFromVsCode()
const report = await project.lintSingleMessage({ message })

if (report.failure){
  return `The message is invalid {report.reason}`
}

```

**Comment by felixhaeberle** [comment]
> apps can provide real-time feedback as user's type without creating a message first

Sounds like a huge benefit and something we should definitely consider. 
@inlang/editor How are you currently handling such cases?

**Comment by samuelstroschein** [comment]
> What I miss here is for the user to specify when the lint rule should be called. Heck even when in which app on which platform.

I don;t understand why a user needs to select when lints run. They run automatically [if a message exists].

**Comment by felixhaeberle** [comment]
This is how it currently works. But when entering a field of 

- external factors: "I want to run a lint rule based on another message changes (variable references)"
- more lifecycle control: "Please only run this lint rule on delete as clean-up"

there are advanced use cases of users I could think of who might want to set up lint rules in different ways.

**Comment by samuelstroschein** [comment]
I don't see a use case for the lifecycle stuff at the moment. For the programmatic linting I see a use case to shorten feedback cycles (provide real-time feedback). Let's focus this discussion on programmatic linting. 

--- 

> external factors: "I want to run a lint rule based on another message changes (variable references)"

This is all dealt with in the SDK. If a message changes, the lint rule is automatically re-executed for the changed message. 

> more lifecycle control: "Please only run this lint rule on delete as clean-up"

Maybe in the future.

**Comment by felixhaeberle** [comment]
Reassigning myself from this as programmatic linting is more of an SDK question.

**Comment by samuelstroschein** [comment]
closing as stale / likely has a duplicate in linear
