### ISSUE TITLE
create tree view for messages

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#1911]
Improved message view:

- See / Edit all messages used in opened file
- Easy access
- Better linting
- Jump to Fink

**Comment by samuelstroschein** [comment]
For linting: build in a nudge to "lint in your ci/cd pipeline via the inlang cli"?

**Comment by felixhaeberle** [comment]
https://www.loom.com/share/5b74a2ba69454dffb9f2cadd74ab34a5

@martin-lysk I'll give you a dedicated update on the performance in a loom.

**Comment by felixhaeberle** [comment]
closed with #1879
