### ISSUE TITLE
rework error management to have custom error collector

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#1912]
The goal of the new error management is:

- all errors in one place
- easy communication around errors for users 
- no error pop-ups disrupting the workflow
- project-specific error handling

**Comment by samuelstroschein** [comment]
@felixhaeberle is this sdk related or only affecting the ide extension?

**Comment by felixhaeberle** [comment]
This is only ide extension related. Error management in the SDK is already in a usage, for now good shape.
