### ISSUE TITLE
[feat] add monorepo support to inlang/badge

### ISSUE THREAD

**Issue by flornkm** [opral/monorepo#1960]
## Problem 
The badge is not available to monorepos yet.

## Proposal
Add a query to select a project for the badge API, e.g. `https://inlang.com/badge?url=github.com/inlang/monorepo&project=relative/path/to/project.inlang`

**Comment by samuelstroschein** [comment]
badge as own service e.g. `badge.inlang.com/github.com/inlang/monorepo&project=relative/path/to/project.inlang` to prevent de-couple the server ?

**Comment by flornkm** [comment]
@samuelstroschein I mean yes, it is already its own service just with a proxy to the website, I think we can and should do that.

**Comment by flornkm** [comment]
Operation successful: https://github.com/opral/monorepo/commit/4cdfa3be593a1a87f05d62e884cc32cf94b5e333
