### ISSUE TITLE
[bug] searching for parrot yields no results

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1970]
### Problem

<img width="1122" alt="CleanShot 2024-01-04 at 12 32 20@2x" src="https://github.com/opral/monorepo/assets/35429197/42699b1b-a5cf-4e54-bd59-e8d37dc7f887">

### Expected behavior

show parrot

### Reproduction

1. go to inlang.com 
2. search for "parrot"

**Comment by flornkm** [comment]
Parrot doesn't have the keyword, this is not a bug. It just wasn't added, I will ping Martin as soon as he's back from vacation.

<img width="567" alt="Screenshot 2024-01-04 at 9 03 58 PM" src="https://github.com/opral/monorepo/assets/92092993/6004841c-b1df-4298-be6c-ff245fe0258e">

**Comment by samuelstroschein** [comment]
@flornkm why does it need a keyword? Parrot has a title and description. I expect to find parrot if i search for "parrot"

**Comment by flornkm** [comment]
@samuelstroschein didn't we already discuss this? I remember that we decided to have keywords as only rule for how something is being listed so the publishers have all the power.

If we would derive that from the title which I remember we already had one time, Parrot would be listed under the plugins category too (but it is only an app, not an inlang plugin :D) or we would need two Algolia instances:

<img width="326" alt="Screenshot 2024-01-04 at 10 26 24 PM" src="https://github.com/opral/monorepo/assets/92092993/b9f6549b-055e-43a0-ad84-9a42142b5a24">

**Comment by flornkm** [comment]
I will look into how I can get this to run, it is a RPC function so I can derive the info if it should search after title + description from the query. Will look into it tomorrow and try to fix that in an uncomplicated way

**Comment by samuelstroschein** [comment]
@flornkm i mean algolia has a category feature https://www.algolia.com/doc/guides/solutions/ecommerce/browse/tutorials/category-pages/

search should not exclude title and description but ofc filter if i am in a particular category
