### ISSUE TITLE
[bug] fink can't open cal.com repo

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1980]
### Problem

<img width="501" alt="CleanShot 2024-01-08 at 09 52 44@2x" src="https://github.com/opral/monorepo/assets/35429197/47d5f690-b2d8-4dd2-9643-82634217cdd6">

### Reproduction

1. OPen https://fink.inlang.com/github.com/calcom/cal.com

**Comment by samuelstroschein** [comment]
@janfjohannes assigned you because "FilesystemError"

**Comment by janfjohannes** [comment]
@samuelstroschein  the fs actually behaves correctly here, this is a bug in /inlang/source-code/sdk/dist/listProjects.js

but i will make a fix

**Comment by samuelstroschein** [comment]
@janfjohannes i assume because a glob mechanism is missing from fs and the implementation of listprojects is hacky now?

**Comment by janfjohannes** [comment]
@samuelstroschein  no because cal.com uses a symlink to a file that does not exist and the lsitprojects function iterates over files with .stat not lstat, but stat  is defined as the stat object of the file that is pointed to by a symlink, so the iteration fails  because stat has to throw

**Comment by janfjohannes** [comment]
update: cal.com had another but wich is currently being fixed by @NiklasBuchfink

**Comment by NiklasBuchfink** [comment]
@janfjohannes The fix for the loading bug is live (https://github.com/opral/monorepo/issues/1993)

I suspect that the migration by the SDK is not recognized as a project by `projectList()` and you will be prompted to create a new project. Is this correct?

**Comment by janfjohannes** [comment]
@NiklasBuchfink  that is my theory, i will test and confirm when my fix for the symlink issue .env/ crash is live, which depends on merging another pr first....
