### ISSUE TITLE
[bug] Lack of Security file

### ISSUE THREAD

**Issue by coderbm1** [opral/monorepo#1984]
### Problem

Hello,
It would be great to see Security.md file  https://github.com/opral/monorepo/security I think. (with at least some contact to the proper Team)

Kind regards,

### Expected behavior

Provided contact for Security issues, or used for example:
https://docs.github.com/en/code-security/security-advisories
https://docs.github.com/en/code-security/getting-started/securing-your-repository
and similar features from the GitHub

### Reproduction

Go to https://github.com/opral/monorepo/security See no way to report security issue.

**Comment by samuelstroschein** [comment]
Good idea. While the readme is created, you can write `hello@inlang.com`

**Comment by samuelstroschein** [comment]
Created a SECURITY.md file https://github.com/opral/monorepo/commit/7cbe057fa982b845e9718c6b0ba421b42a1e14ff. @coderbm1 Please close this issue if think this is enough or express what is missing

**Comment by coderbm1** [comment]
Awesome! 🎉 Thank you so much for quick action and professional approach ✨
