### ISSUE TITLE
fink doesn't prompt the user to create a new project

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1993]
### Problem

Fink shows no error when a repo contains no `*.inlang` repo. reported by @jldec:

> The Fink UI doesn't tell you why the cloning is not working - It just spins (this should be easy to fix). The links at the top of the Fink page and the card on the inlang landing page lead to docs [here](https://inlang.com/m/tdozzpar/app-inlang-editor) and [here](https://inlang.com/g/6ddyhpoi/guide-nilsjacobsen-contributetranslationswithfink) which don't mention the need for a project.inlang directory. Eventually I clicked on the "Open" button which goes to https://fink.inlang.com/ and there I found The i18n editor, requires a project.inlang folder in your repository. 😀

### Expected behavior

Show the user that a project needs to be created cc @flornkm (you are working on create new project)

### Reproduction

1. Open https://fink.inlang.com/github.com/jldec/readme-is-all-you-need

**Comment by samuelstroschein** [comment]
@NiklasBuchfink this bug has likely been introduced in #1935

**Comment by NiklasBuchfink** [comment]
This should be fixed now. It was indeed the `projectList()`. If there is no project, the value of `project()` will always be undefined. It is now dependent on the state of the `projectLIst()`
