### ISSUE TITLE
Improve Paraglide onboarding

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#1995]
## Problem 
After running `paraglide-js init` to bootstrap the paraglide setup, users are often confused on how to continue. It's not clear that:
- `project.inlang/settings.json` is where you configure which languages are available
- `project.inlang/settings.json` is where you configure the location of where messages are stored
- `messages/{lang}.json` is where messages are stored by default. The `messages` folder doesn't even get created.

## Proposal
There are a few thins we can do to improve the onboarding.
1. Inform the user they should read `project.inlang/settings.json` at the end of the `init` cli command
3. Generate a `messages/en.json` if a _new_ project is being generated. This topic has come up before, and I believe the reasoning for not doing this was that developers should use the IDE to add messages instead of editing a file by hand. Unfortunately, the IDE doesn't work until that file exists, so everyone always needs to add it manually anyways.

**Comment by samuelstroschein** [comment]
The second point will become redundant after #1844. So don't hack anything in paraglide. This issue will auto resolve in 1-3 weeks

**Comment by LorisSigrist** [comment]
@samuelstroschein What do you think of the first point? I've had a couple interactions where people were unaware of the settings file

**Comment by LorisSigrist** [comment]
The rest of this issue will not be implemented for the reasons Samuel stated above
