### ISSUE TITLE
[bug] ID stripped from URL in editor page leads to incorrect resolution in monorepo

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#1997]
### Problem

ID stripped from URL in editor page leads to incorrect resolution in monorepo and doesn't get resolved correctly because information about the project path is not passed to resolve.

> This blocks #1911 from being finished.

### Expected behavior

It should resolve with the following project:
<img width="1112" alt="Bildschirmfoto 2024-01-10 um 15 10 08" src="https://github.com/opral/monorepo/assets/34959078/65a89ff4-7206-44a2-9ef9-56bcd9c4bdc3">

### Reproduction

Test it with this: https://inlang.com/editor/github.com/inlang/monorepo?id=client-page:title

### Other information

Chrome Version 120.0.6099.199 (Offizieller Build) (arm64)
MacOS 13.6 (22G120)

**Comment by felixhaeberle** [comment]
**Clarification**

There is a project url parameter: `?project="/path"`. 
But for some reason, it doesn't get applied when selecting a project. See the screenshot in the issue.

**Comment by NiklasBuchfink** [comment]
@flornkm for context, the project is not set in the url of Fink

**Comment by NiklasBuchfink** [comment]
This should be fixed now by @flornkm with https://github.com/opral/monorepo/commit/1432741208f22f54de369b0ffcd98a17973d645c
