### ISSUE TITLE
[bug] improve error messages in `manage.inlang.com`

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#1999]
### Problem

The project selection in `manage.inlang.com` seems broken.

### Expected behavior

Let me select my project.

### Reproduction

1. https://manage.inlang.com/?repo=github.com/inlang/monorepo
2. Click on the first "/inlang/source-code/end-to-end-tests/inlang-nextjs/project.inlang"
3. Broken site.

<img width="831" alt="Bildschirmfoto 2024-01-10 um 15 42 59" src="https://github.com/opral/monorepo/assets/34959078/76a62e8e-a2c2-43c2-83ad-a4522d293ac6">

### Other information

Chrome Version 120.0.6099.199 (Offizieller Build) (arm64)
MacOS 13.6 (22G120)

**Comment by felixhaeberle** [comment]
@flornkm Oh, I see, this is probably because of the locally referenced modules. 
Would it be possible to display more specific errors here?

**Comment by flornkm** [comment]
@felixhaeberle these projects are for testing, no other user will run into these issues as far as I know.
The links are relative paths and we decided to force them to use our official jsdelivr ones, what would be more clearer for you in the message?
