### ISSUE TITLE
View and edit LanguageTags on `manage.inlang.com`

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/monorepo#2003]
## Context
We have a hard time communicating how to get started and set up an inlang project to the users needs. Creating the project dir with a `setting.json` is a critical part of the process.

## Proposal
Manage allows you to view, add or remove modules of an existing project. It makes sense to show and edit the `sourceLanguageTag` and `languageTags` properties in the same place.

It is another step to create and edit the inlang projects completely via manage and edit everything in the settings file. This should be desired to give the best setup experience possible.

---
As discussed with @NilsJacobsen @flornkm

**Comment by NiklasBuchfink** [comment]
@NilsJacobsen @flornkm Pls assign yourself if you are responsible for this task.

**Comment by samuelstroschein** [comment]
The context seems misleading. The problem you are having is that languages can't be changed via a UI (manage.inlang.com) correct?

**Comment by samuelstroschein** [comment]
Being the devil here and assigned both @NilsJacobsen and @flornkm to *really* make sure this issue is handled
