### ISSUE TITLE
`manage` should set project in root as default if there is one

### ISSUE THREAD

**Issue by flornkm** [opral/monorepo#2004]
## Problem 
You always have to select `inlang/manage`.

## Proposal
Do it like Fink: Set the project in the root as default if nothing is selected and it exists.

**Comment by felixhaeberle** [comment]
+1 I would love to see this!

**Comment by flornkm** [comment]
Implemented with https://github.com/opral/monorepo/commit/e4724aafd49701609472d03349a222534567390c
