### ISSUE TITLE
Improve Message Lint Rule pages with more information

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#2008]
### Problem

Dev's are lost with the configuration of lint rules, they do not find the relevant information like the default lint rule level or the customization option to adjust the level (and in the future other properties aswell).

https://discord.com/channels/897438559458430986/1194957255263666196/1195342177363034313

<img width="735" alt="Bildschirmfoto 2024-01-12 um 13 29 13" src="https://github.com/opral/monorepo/assets/34959078/4664f86f-bdd6-4022-b97e-f20e3335ad01">

https://discord.com/channels/897438559458430986/1194243685848731668/1194396438742958090

<img width="518" alt="Bildschirmfoto 2024-01-12 um 13 35 47" src="https://github.com/opral/monorepo/assets/34959078/78231947-0a6b-4119-84e8-f9b57dfdb320">

---

Therefore people: 

a.) are getting confused or do not find the information 
b.) what results in question overflow in Discord

## Proposal

> Improve Lint Rule pages with more information so people don't have to ask constantly in Discord

**Add (back) the information about how to manually set it up and general information about default lint rule level & lint rule settings.**

`https://manage.inlang.com` is really great but it currently doesn't handle those kinds of information & functionality. Even with the configuration layer of `manage` in place, it would be very beneficial to have this information on the lint rule pages.

**Comment by NilsJacobsen** [comment]
What we should add:

- [ ] Add default level on the lint pages
- [ ] Show available module settings

**Comment by NilsJacobsen** [comment]
Added it with https://github.com/opral/monorepo/commit/130cfed17ce767446c6e7f7f64920f3bb3453a5e

**Comment by felixhaeberle** [comment]
Cool! Thanks @NilsJacobsen 🥳
