### ISSUE TITLE
paraglide JS is missing the TS symbol on NPM

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2018]
## Problem 

Paraglide JS is typesafe but shows no TS symbol on NPM, which might lead people to think that paraglide JS is not typesafe.

<img width="911" alt="CleanShot 2024-01-14 at 23 50 31@2x" src="https://github.com/opral/monorepo/assets/35429197/677fba25-8f66-43ed-9d28-ad754ef7596d">

## Proposal

Figure out why the TS icon is not showing to increase Paraglide's downloads/adoption.

**Comment by LorisSigrist** [comment]
This is very likely because Paraglide doesn't have a JS entry point, since it's just a CLI, so as far as npm is concerned there is nothing that could be typesafe. 

If we want the typesafety symbol there we will need to standardise a programmatic API for paraglide's usage & expose types for it.

**Comment by LorisSigrist** [comment]
A "hack" to get the symbol might be to add an empty default export & provide types for it

**Comment by samuelstroschein** [comment]
@LorisSigrist do you think the TS badge will contribute to paraglide adoption? If yes, the hack soundsg good. If not, close this issue
