### ISSUE TITLE
[bug] Dropdowns are cut off on `manage.inlang.com`

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#2019]
### Problem

The repository and project dropdowns at the top of the page are cut off. Who doesn't love CSS

https://github.com/opral/monorepo/assets/43482866/6afb2681-032e-4417-bef8-532d88ddff54

### Reproduction

1. go to `manage.inlang.com` and open a repo.
2. Try using a Dropdown

### Other information

Arc Browser 120 on MacOS

**Comment by NilsJacobsen** [comment]
@flornkm are you available for that today?
