### ISSUE TITLE
[bug] Card images are cut off at smaller screen sizes

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/monorepo#2022]
### Problem

The image no longer transfers its message when it is cut off like this.

![image](https://github.com/opral/monorepo/assets/59048346/94c4a72b-a65c-4b9c-800f-2c4242fed8bc)

### Expected behavior

Centered and smaller instead

### Reproduction

Go to "https://inlang.com/c/lint-rules"

### Other information

Browser: Edge Chromium

**Comment by flornkm** [comment]
@NilsJacobsen you were going to work on Lint Rules today anyway is this correct?

**Comment by NilsJacobsen** [comment]
This is fixed ✅
