### ISSUE TITLE
[bug] VSCode extension delete old messages sometimes

### ISSUE THREAD

**Issue by paoloricciuti** [opral/monorepo#2027]
### Problem

Sometimes when i use the VSCode extension it deletes the content of my en.json to replace it only with the newly added message (or with all the messages that i've added recently)

https://github.com/opral/monorepo/assets/26281609/220b8c26-26cc-4827-b030-0a197df67dd1

### Expected behavior

The extension should add the new translation without loosing the content of the file.

### Reproduction

1. open vscode with paraglide and `message` plugin for storage
2. create an `en.json` filled with values
3. try to add a new value via the extension

Note: i don't know if this is a proper reproduction unfortunately, i'm opening this following a discord conversation to keep track of the issue...i'll try to reproduce consistently in the near future.

### Other information

It seems the messages lives in some sort of state that get's constantly stringified and written to the translation file. Probably the problem doesn't exist for as long as vscode persist the one instance of the extension open (?). Maybe the simple fix could be to just append to the file or reading it before writing instead of keeping a list in memory?

N.B. those are all assumptions, i don't know the internals of the extension 😄

**Comment by samuelstroschein** [comment]
@opral/inlang-ide-extension if the ide extension only calls `query.*` methods from the @opral/inlang-sdk, the bug is in the SDK. 

Assigning @felixhaeberle to this issue as default. Felix hand off to @jldec if the bug is rooted in the SDK. 

_likely related to #https://github.com/opral/monorepo/issues/1772_

**Comment by felixhaeberle** [comment]
> the ide extension only calls query.*
✅
