### ISSUE TITLE
move fink, manage, and badge to changeset based deployment

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2029]
## Problem 

Fink deploys on every commit to main, which leads to: 

- deployment of unreleased changes yet e.g. the SDK
- the infamous "don't push on Friday" problem 

## Proposal

1. Don't auto-deploy on changes.
2. Force changesets 
3. Have a CI action that deploys fink when the version increases

- [ ] fink
- [ ] manage
- [ ] badge

cc @janfjohannes (because we discussed this)

**Comment by samuelstroschein** [comment]
@NiklasBuchfink agree?

**Comment by NiklasBuchfink** [comment]
Let's do this 👍🏼 I see the benefits and we need better quality this year.

**Comment by janfjohannes** [comment]
@samuelstroschein  thanks its a really good idea, render will internally build a docker image for each service that is bumped in version and keep that in the deployment history, so if this works out, this is effectively like a small version of the docker setup i had in mind.  i think the next step is to add the changeset workflow into our own ci as the github action runner is very slow and noisy on prs. it should not be too hard to do.

**Comment by janfjohannes** [comment]
@samuelstroschein  sure lets give a try if we can replace nx with rush and get changeset features on top

**Comment by NilsJacobsen** [comment]
@NiklasBuchfink assigned you as you are already working on version / hash display in fink

**Comment by samuelstroschein** [comment]
duplicate in linear https://linear.app/opral/issue/FINK-5/move-fink-manage-and-badge-to-changeset-based-deployment
