### ISSUE TITLE
Paraglide: Autodetect VsCode during `init`

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#2032]
`paraglide-js init` asks if you are using VsCode, so that it knows if it should add/edit the `.vscode` settings. There is a cheap and reliable way to detect if the command is being run inside the VsCode terminal. We can check if the `$TERM_PROGRAM` environment variable is equal to `vscode`. In that case I say we should skip the question and default to yes.

**Comment by samuelstroschein** [comment]
@LorisSigrist nice one!
