### ISSUE TITLE
feat[manage]: getting started via `/create` user analysis

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/monorepo#2033]
## How we want to do project creation cross app?

@NiklasBuchfink and I did a little use case mapping (sry it's a bit long):
https://www.loom.com/share/c3121bda124444adaea4a64994f5ec4c?sid=a22bbb20-bc57-4980-8014-78af2932d730

## Insights

- Create process should be straight forward for Fink
- We can cross-sell paraglide to green field users
- IDE Extension & CLI use cases need to pull after manage flow (that needs to be communicated)
- A ecosystem member-first approach (fast if project is already there, if failed you can create) is beneficial for feeling extremely empowered once project is setup.
- For Fink and Parrot it should look similar 

### Unified process
![image](https://github.com/opral/monorepo/assets/59048346/d1fbfd5c-08cc-4e29-9d7b-aebe2c5e67fe)

## Question: Should we proceed with uniformed manage flow vs cli command that can be executed locally?

This question came from that insight -> "IDE Extension & CLI use cases need to pull after manage flow (that needs to be communicated)"

@opral/inlang-fink @opral/inlang-plugins @opral/inlang-ide-extension @opral/inlang-cli @opral/inlang-sdk @opral/inlang-martketplace-infrastructure

**Comment by NiklasBuchfink** [comment]
@NilsJacobsen I think we can close this as it is outdated after the introduction of "every app can start and create a project".
