### ISSUE TITLE
evaluate rush to get our monorepo problems under control

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2039]
## Problem 

Constant "devops" problems with changeset, nx, and package resolution: 

- long build times, caching flaky
- changeset is unmaintained and sometimes (feels) buggy 

## Proposal 

_Originally posted by @samuelstroschein in https://github.com/opral/monorepo/issues/2029#issuecomment-1893955987_

Let's evaluate https://rushjs.io/ before we build too much infra for changesets. 

- changesets is unmaintained
- rush seems to solve many problems all at once
- rush has baking from Microsoft, TikTok, Big tech (will not go unmaintained)

### Requirements

 - [ ] prevents merges to main with missing changeset
 - [ ] doesn't require build before dev is starting (dev scripts are invokes in order of the dependencies)
 - [ ] caching works
- [ ] caching "just works"
- [ ] [sub-project selection](https://rushjs.io/pages/developer/selecting_subsets/#--to) works and avoids workarounds like https://github.com/opral/monorepo/blob/9212331266d3c128239b72897d26b74a2b775ed9/package.json#L10

**Comment by samuelstroschein** [comment]
@janfjohannes who should tackle this one? Should I, you, or @LorisSigrist (because he worked with GH Actions) look into this?

**Comment by janfjohannes** [comment]
@samuelstroschein  i just had a first look  but tbh rush seems really like the docu sais for large enterprises. its very verbose and requires a fresh repo with moving over packages one by one as far as i can tell.  an empty rush project with no added packages is allready 12 configuration files.

**Comment by janfjohannes** [comment]
@samuelstroschein  on the other hand changesets seems to have commits last month, so not sure where you got that it is unmaintained. the commands seem to work fine , as far as i can tell our issues stem mostly from the github action begin bad not from the cli tool itself.

**Comment by samuelstroschein** [comment]
@janfjohannes

>  its very verbose and requires a fresh repo with moving over packages one by one as far as i can tell. an empty rush project with no added packages is allready 12 configuration files.

Yep, that's why we avoided it. Something should do a thorough check. I am assigning myself to avoid resources being drained from growing apps and so that you can push lix features. 

> on the other hand changesets seems to have commits last month, so not sure where you got that it is unmaintained.

- changeset has no full-time maintainer. the issues are piling up https://github.com/changesets/changesets/graphs/contributors
- rush has multiple full time PAID maintainers https://github.com/microsoft/rushstack/graphs/contributors


![CleanShot 2024-01-16 at 15 24 02@2x](https://github.com/opral/monorepo/assets/35429197/8e35bf9a-9abc-4574-bc20-84a242677946)

_Changeset issues are piling up https://ossinsight.io/analyze/changesets/changesets#issues_

**Comment by janfjohannes** [comment]
@samuelstroschein  changesets has extremely limited scope, it does one thing and one thing only and it is nowhere near as complicated as what an nx or rush needs to do so this is not worrying me unless we really run into bugs of the tool. 

looping in @LorisSigrist   as we both feel rush will  most likely not solve our issues

**Comment by samuelstroschein** [comment]
@LorisSigrist why do you feel that rush would not solve issues we are having in the monorepo? 

@janfjohannes my motivation for rush also stems from the fact that you are diverting lix's development by not running the entire repo and hinting that you want to get lix out of the repo because build times take too long. long build times and all issues related with it is exactly what rush is solving while keeping monorepo benefits

**Comment by samuelstroschein** [comment]
Example of changeset having struggle to keep up with issues https://github.com/opral/monorepo/issues/2055#issuecomment-1898545949

**Comment by samuelstroschein** [comment]
Rush is not suited for our monorepo. 

- requires opionated setup of monorepo (can’t be adopted incrementally) 
- complicated to setup and operate
	- tons of config files
- somewhat outdated given PNPM and NPM workspace features
	- runs own workspace solution instead of leveraging PNPM’s or NPM’s
