### ISSUE TITLE
[bug] <Getting 'Forbidden' when running machine-translate>

### ISSUE THREAD

**Issue by MaxMillington** [opral/monorepo#2041]
### Problem

I'm running machine translate on my app, for many of my keys, I'm getting a 'Forbidden' message e.g:

` ERROR  Couldn't translate message "addConcentratedLiquidity.managedDescription": Forbidden`

Am I doing something wrong?

### Reproduction

You can see the PR [here](https://github.com/osmosis-labs/osmosis-frontend/pull/2697)

**Comment by samuelstroschein** [comment]
@MaxMillington I assume that the machine translation of a large number of messages might trigger too many parallel requests for google translate (in your case approx 3000 messages). 

@felixhaeberle can you implement batched requests of max 500 in the CLI?

**Comment by MaxMillington** [comment]
@samuelstroschein is that per day? per hour?

**Comment by samuelstroschein** [comment]
@MaxMillington per second. I assume that running the command triggers N parallel requests. N = 3000 in your case. That might be too high for G Translate. 

I hope to mitigate this problem by batching the requests. 

That said, @felixhaeberle can you look into the max rate of parallel requests to get a number in the g translate docs?

**Comment by MaxMillington** [comment]
@samuelstroschein interesting. for additional context, I ran `machine-translate` and it translated about half the file, ran it again and it translated another 40%, and the third time I started to get the forbidden error. Just ran again and still getting the forbidden error on the same keys. It's weird because it's not like the last keys in the json get the error, but it's seemingly random keys on the list.

**Comment by felixhaeberle** [comment]
The quotas & limits can be seen here: https://cloud.google.com/translate/quotas#content — we probably have to inspect our usage in the Cloud console and see if we run in any kind of limit.

**Comment by MaxMillington** [comment]
@felixhaeberle It worked today. Thanks!

**Comment by felixhaeberle** [comment]
@samuelstroschein due that it worked today, should we still batch the messages to 100?

**Comment by samuelstroschein** [comment]
@felixhaeberle let's assume that the google API had issues
