### ISSUE TITLE
Communicate new ID and storage concept.

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/monorepo#2043]
## Proposal

- [ ] Add a Id and storage section in the SDK docs https://inlang.com/documentation.
- [ ] Eventually adjust communication when users create new messages in the apps.

> documentation needs to educate that "aliases" are legacy for existing projects AND SHOULD NOT be used for new projects

**Comment by samuelstroschein** [comment]
what is a storage section?

**Comment by NilsJacobsen** [comment]
A place where we communicate the message storage for people who want to build with it. I think many people will wonder why we are doing it and not saving json (so was/is Jürgen as far as I know). So explaining way this is good and how it is been done would be good. Although I need to admit that we are talking about a future SDK doc, that should be set up when sdk is built.

**Comment by samuelstroschein** [comment]
is this required if we communicate a project as "a file"? see https://www.loom.com/share/5f0b90b9396f46a4b93d7f8b6408311b?t=130&sid=e65c352a-ba96-453a-bc36-956a2037e150

**Comment by NilsJacobsen** [comment]
I don't think that help the dev understand that they don't need to use a plugin as a day 1 user. And also the unique ids are not communicated there.

I think we need these sections in the message concept:
- What is a message
- storage - you can use the ootb storage or configure a plugin
- Ids - human readable ids
- depricated aliases

That's all it needs

**Comment by samuelstroschein** [comment]
> I don't think that help the dev understand that they don't need to use a plugin as a day 1 user.

You seem to invert the default here. The default is "why do I need a plugin", not "oh I don't need a plugin". 

> storage - you can use the ootb storage or configure a plugin

Storage is not configurable after #1585 anymore. However, you can import and export messages. Tiny but important difference. 

## Proposal 

1. I'll update the message docs to include what is a message, ids, aliases.
2. How an inlang project stores messages belongs to `concept/project`. Thus, change the title of this issue to "explain storage of messages in inlang project concept"

@NilsJacobsen agree on the proposal?

**Comment by NilsJacobsen** [comment]
I agree. I didn't want to push plugins, I just think it's great to let them know that we handle everything. But jep let's do that on the `concept/project` page.
