### ISSUE TITLE
[bug] <inlang/sdk-js not works with SvelteKit 2.0>

### ISSUE THREAD

**Issue by Shwallbesa** [opral/monorepo#2059]
### Problem

**inlang/sdk-js not works with SvelteKit 2.0**

Log: 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.0.1
npm ERR! Found: @sveltejs/kit@2.3.5
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"^2.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @sveltejs/kit@"^1.0.0" from @inlang/sdk-js@0.11.8
npm ERR! node_modules/@inlang/sdk-js
npm ERR!   @inlang/sdk-js@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

OS: Windows 10
Node: v20.10.0

### Reproduction

`npm create svelte@latest my-app`
`npm i @inlang/sdk-js`

### Other information

OS: Windows 10
Node: v20.10.0

**Comment by samuelstroschein** [comment]
@Shwallbesa the "sdk-js" has been deprecated for several months. Please migrate to https://inlang.com/m/gerre34r/library-inlang-paraglideJs
