### ISSUE TITLE
make project id non-optional when every project is guaranteed to a project id

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2063]
https://github.com/opral/monorepo/blob/6b6f91500d124410852a923f8c0d0eba5e36128e/inlang/source-code/sdk/src/api.ts#L37-L41

**Comment by jldec** [comment]
see https://github.com/opral/monorepo/issues/2101#issuecomment-1911907633
waiting for definitive way to ensure that projects have a project id. - #2063
