### ISSUE TITLE
enforce project id generation (which requires a repo to exists)

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2069]
#2013 opens the possibility to enforce project ids and get rid of conditional logic and bugs like https://github.com/opral/monorepo/issues/2070

## Task

Make `project.id` not potentially undefined

https://github.com/opral/monorepo/blob/27b1307868aaf6baf68fe4f6c7cb058f7931dbd1/inlang/source-code/sdk/src/api.ts#L40-L42

**Comment by jldec** [comment]
see https://github.com/opral/monorepo/issues/2101#issuecomment-1911907633
waiting for definitive way to ensure that projects have a project id. - #2063
