### ISSUE TITLE
unexpected return type of `repo.getOrigin()`

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2079]
## Problem 

`repo.getOrigin()` returns "unknown" if a repo can't be found (1), conflicting with the type definition of `ReturnType<string>` (2), aka an origin always exists.

![CleanShot 2024-01-22 at 22 41 31](https://github.com/opral/monorepo/assets/35429197/45c12202-db24-4f9e-8b8b-fb66019848c0)

## Proposal

Change the return type of `repo.getOrigin()` to be `string | undefined` to align with "maybe an origin exists" line of thought.

**Comment by felixhaeberle** [comment]
Agree!

**Comment by samuelstroschein** [comment]
closing as done becuase prio list says its done
