### ISSUE TITLE
move `parseOrigin` from `@inlang/telemetry` to `@lix-js/client`

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2081]
## Problem 

@janfjohannes the `parseOrigin` function from `@inlang/telemetry` should likely move to lix

- misplaced in @inlang/telemetry (which is supposed to be deprecated)
- needed for several apps (ensures one origin)

https://github.com/opral/monorepo/blob/c8db6b71ba51d27ed94751958b21cde8882c11e9/inlang/source-code/telemetry/src/utilities/parseOrigin.ts

## Proposal

- [x] 1. Move the function to `@lix-js/client` and replace imports
- [x] 2. `parseOrigin` should return undefined instead of "unknown" similar to #2079

**Comment by janfjohannes** [comment]
@samuelstroschein  this was allready moved to lix a long time ago (thats how the "unknown" ended up in the lix api), just the imports have to be fixed and the code from telemetry removed.

**Comment by samuelstroschein** [comment]
@janfjohannes `parseOrigin` doesn't exist on the repo API, nor is it exported from lix though. 

**context**

- `getOrigin` is not suited as `parseOrigin` replacement. `parseOrigin` acts as `stripOriginFromMetadata` (good rename!). two different use cases
- `stripOriginFromMetadata` should be it's own exported function (no need to bloat `repo.*` API for this)

**Comment by janfjohannes** [comment]
@samuelstroschein  sorry i dont unsderstand what the usecase is why getOrigin is no replacement of parseOrigin.    the example you gave is exactly what getOrigin does if a m not mistaken.

**Comment by samuelstroschein** [comment]
@janfjohannes 

- `getOrigin()` gets the unfiltered origin as stated in the repository. if we process it, it will become useless in envs where metadata such as keys are important.
- `stripMetadataFromOrigin()` removes metadata such as keys from an origin. needed to implement `inlang open editor` logic. see this test case https://github.com/opral/monorepo/blob/7691f6b50863950cbf32f20496d28ef9660d0a61/inlang/source-code/telemetry/src/utilities/parseOrigin.test.ts#L63-L78

**Comment by felixhaeberle** [comment]
Subscribing to this issue to get notified. VSC extension needs this change & a cleanup in this space too.
