### ISSUE TITLE
[bug] SvelteKit Adapter Preprocessor - Continuation-Blocks aren't being Walked properly

### ISSUE THREAD

**Issue by xmlking** [opral/monorepo#2098]
### Problem

I am using latest versions with sveltekit project.
```json
"@inlang/paraglide-js": "1.2.1",
"@inlang/paraglide-js-adapter-sveltekit": "0.2.2",
```
All links are updated when I switch language, except following link.

https://github.com/xmlking/spectacular/blob/main/apps/console/src/lib/components/layout/header.svelte#L244

<img width="826" alt="image" src="https://github.com/opral/monorepo/assets/627951/ecab778c-a46b-4e8a-8a8a-4668b34cde9b">

To reproduce you can run this app: https://github.com/xmlking/spectacular/tree/main/apps/console

Other question:
what is the recommended approach to retain lang user selected, when  we have to redirect users to Google for OAuth Login and come back to the site?

### Expected behavior

following link should also updated with lang switched. 
```svelte
		<!-- Login/Avatar -->
		<section class="flex items-center justify-between gap-4">
			{#if user}
				{#if user?.avatarUrl}
					<Avatar src={user?.avatarUrl || undefined} />
				{:else}
					<Avatar initials={user.email} />
				{/if}
			{:else}
				<a href="/auth/signin" class="variant-filled-primary btn"
					>{m.auth_labels_signin()}</a
				>
			{/if}
		</section>
	</svelte:fragment>
```

### Reproduction

To reproduce you can run this app: https://github.com/xmlking/spectacular/tree/main/apps/console

**Comment by LorisSigrist** [comment]
<img width="645" alt="Screenshot 2024-01-24 at 11 12 08" src="https://github.com/opral/monorepo/assets/43482866/77a71607-1db8-4f26-8b78-56f5ef290dab">

Is it possible that the link is inside a modal, which, judging by your setup, are outside the `<ParaglideJS>` component? We use Svelte's Context API to pass the `i18n` config from the `<ParaglideJS>` component to the places where `a` tags are used, so it's important to make sure the `<ParaglideJS>` wraps everything. 

> what is the recommended approach to retain lang user selected, when we have to redirect users to Google for OAuth Login and come back to the site?

That depends on the Provider, some let you register language-specific return URLs. Otherwise I would store the language in a cookie when leaving & read + redirect that cookie in your return-URL-handler.

**Comment by xmlking** [comment]
I wrapped everything including  header with in "<ParaglideJS>"

the header section is 
‹svelte: fragment slot="header">
<Header user=<data?.user} />
</svelte: fragment>

interestingly other links in header got translated but the login button link is the only one not getting translated

**Comment by LorisSigrist** [comment]
This is very odd, I can reproduce the issue & it really is a bug, but I don't know what exactly is causing it. I'll keep you updated

**Comment by xmlking** [comment]
> UPDATE: I figured out what's going on. The Preprocessor wasn't walking the parsed AST properly! It was skipping `{:else}` blocks. Apparently blocks that have continuations, such as `{#if}` and `{#await}` put the children of their continuations (`{:else}` , `{:then}`) into different branches & those aren't being crawled.
> 
> I'll fix this & add a bunch of tests to avoid regressions. Thanks for catching this & sorry for the inconvenience

Thanks Loris, totally understand,   many edge cases  has to be though of and handled to make this lib simple to use by developers.

**Comment by LorisSigrist** [comment]
Thanks for understanding. I hope to release the fix today!

In the meantime you could work around this by placing the `/signin` link in it's own component & then putting that component in the `{:else}` block.
