### ISSUE TITLE
support `getTranslation` object syntax for `next-intl` plugin

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#2110]
## Problem

[The object form of `getTranslations`](https://next-intl-docs.vercel.app/docs/environments/metadata-route-handlers#metadata-api) is currently not supported and results in a Error is displayed (e.g. `getTranslations({locale: 'en', namespace: 'IndexPage'})`)

There are already users in GitHub which are already complaining about this for i18n-ally, and we could be a great (maintained) alternative.

<img width="696" alt="Bildschirmfoto 2024-01-24 um 20 56 48" src="https://github.com/opral/monorepo/assets/34959078/a0ea9aea-0f37-4467-a958-b318d71d90af">

https://github.com/opral/monorepo/blob/99bf2e46cf2a7257f9b9928145aaafc7124b640d/inlang/source-code/plugins/next-intl/src/ideExtension/messageReferenceMatchers.ts#L157-L173

## Proposal

Make the parser more versatile to also parse the object inside `getTranslations` and determine the namespace from there.

cc @NilsJacobsen @amannn

**Comment by felixhaeberle** [comment]
@NilsJacobsen As you have originally developed the plugin, can you take over? Would also be a great opportunity to get in touch with the revamped vsc extension codebase.

**Comment by felixhaeberle** [comment]
@NilsJacobsen If you are at it, can you also support the function syntax here:
https://github.com/lokalise/i18n-ally/pull/1048#issuecomment-1890810041

like:
`t.rich`
`t.markdown`
`t.raw`

Or does this already work?

**Comment by felixhaeberle** [comment]
@NilsJacobsen can this be closed?

**Comment by NilsJacobsen** [comment]
these are not supported, but we can also close this and open a discussion when someone asks about this.

```
t.rich
t.markdown
t.raw
```

**Comment by NilsJacobsen** [comment]
Let's wait until someone requests this feature.

**Comment by 0-don** [comment]
yes this is a missing feature
