### ISSUE TITLE
feat[ide-extension]: quick jump to message in current file

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/monorepo#2123]
### Feature request: quick jump to message in current file

Context in Loom:
https://www.loom.com/share/4c893c33c3394d308e45edc4820c2ea4?sid=c1568acc-273f-4cb3-8574-c4def0c18772

@opral/inlang-ide-extension

**Comment by samuelstroschein** [comment]
default assigning @felixhaeberle

**Comment by felixhaeberle** [comment]
this is not possible yet and if we implement it, this would be naively implemented (not recognizing double mentioned messages in one file etc.)

**Comment by NilsJacobsen** [comment]
If this is not possible yet, no worries, I leave it to you. Just wanted to let you know what I thought when using it.

**Comment by samuelstroschein** [comment]
close as not a prio?

**Comment by felixhaeberle** [comment]
@NilsJacobsen great (and fast) progress here. 🥳 what would be the best UX here?

https://github.com/opral/monorepo/assets/34959078/cc23d493-abd5-40fc-b9ea-2c566f417acb

### Suggestion
-> Click on #: Scrolling to message(s)
-> Click on ID: Opening the collapsible?

Currently, it does both things at the same time but that's a bit wild. 

Pro: Multiple clicks on the # could then also jump to like the second same id in the same file if there are 2 and the # is often used as a kind of reference sign. What do you think?
Con: Discoverability of the # functionality isn't that good (I can do a hover to fix that?)

**Comment by samuelstroschein** [comment]
@felixhaeberle 

1. add a button next the message id for higher discoverability
2. move open in fink button to the message id button bar to declutter the UI. opening a message in fink for all languages seems OK
3. change the "open in fink" button icon to a bird head to avoid conflicts with the icon for "jump to source" 


![CleanShot 2024-01-29 at 21 02 45@2x](https://github.com/opral/monorepo/assets/35429197/83f57412-f70d-44a2-a972-7896ac4c958d)

**Comment by felixhaeberle** [comment]
@NilsJacobsen what do you mean with "like Figma"?

**Comment by NilsJacobsen** [comment]
In the figma tree in the sidebar u get the hide and lock option only by hovering.

**Comment by felixhaeberle** [comment]
update: we will merge this today. 🔥

I now settled on those two icons for simplicity. 
-> magnet: jump to message
-> external link: fink

introducing custom icons in vscode is out of scope for this issue.
there is no easy way to achieve this completely (think custom themes/various colors).

<img width="352" alt="Bildschirmfoto 2024-01-30 um 15 00 51" src="https://github.com/opral/monorepo/assets/34959078/ac06bb34-7143-461c-b8d4-19d94ee00697">
<img width="347" alt="Bildschirmfoto 2024-01-30 um 15 01 11" src="https://github.com/opral/monorepo/assets/34959078/4fcac4db-0641-4c46-b48b-cf09d0787a6d">

**Comment by NilsJacobsen** [comment]
haha love the magnet 👍

**Comment by samuelstroschein** [comment]
@felixhaeberle no option to have a bird head icon for fink?

**Comment by felixhaeberle** [comment]
@samuelstroschein This is in the webview so an icon is possible but hacky – has to be color-switched with a CSS mask.

@NilsJacobsen @NiklasBuchfink Do you have a bird head icon which looks nice and fits the style?

**Comment by NilsJacobsen** [comment]
That would also presuppose that the user know fink. If they don't, an external arrow may make more sense to them.
