### ISSUE TITLE
[feat] Detect if branch is protected

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/monorepo#2125]
## Problem 
We do not know whether a branch is protected or not. Therefore, users try to push changes to a protected branch, get an error message and lose their changes.

## Proposal

Extend the `Repository` type of lix with a `isProtected: boolean` type.

With `isProtected` Users can then be prompted to:
- work on a fork and open a PR or
- switch to another branch

**Comment by samuelstroschein** [comment]
closing in favor of lix on sqlite https://opral.substack.com/p/accelerate-by-years-part-iii-lix
