### ISSUE TITLE
GET https://registry.npmjs.org/@inlang%2Ftelemetry: Not Found - 404

### ISSUE THREAD

**Issue by Rar9** [opral/monorepo#2129]
### Problem

pnpm install -D @inlang/cli
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@inlang%2Ftelemetry: Not Found - 404

This error happened while installing the dependencies of @inlang/cli@2.10.1

@inlang/telemetry is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer npm_[hidden]

### Reproduction

pnpm install -D @inlang/cli
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@inlang%2Ftelemetry: Not Found - 404

This error happened while installing the dependencies of @inlang/cli@2.10.1

@inlang/telemetry is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer npm_[hidden]

### Other information

chrome

**Comment by samuelstroschein** [comment]
fixed in https://github.com/opral/monorepo/pull/2128
