### ISSUE TITLE
[feat] Add branch & project support to badge 

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/monorepo#2138]
## Problem 

The badge can only be displayed for the first `project.inlang` project in the main branch.

## Proposal

Extend the badge service and its product page functionality to support the selection of branches and projects like manage.inlang.com and fink.inlang.com.

**Comment by NiklasBuchfink** [comment]
cc @NilsJacobsen Add requirements regarding the GH action if we want to use the badge for this purpose.

**Comment by samuelstroschein** [comment]
I think this issue can be closed. 

- The badge already supports project selection.

```
https://badge.inlang.com/?url=github.com/opral/monorepo&project=/project.inlang
```

-  branch support seems irrelevant for now. use the badge for the main branch. build a dedicated (simpler) app for the github action

**Comment by NiklasBuchfink** [comment]
I agree, we should not use it for the GH action 👍  Therefore the branch support is not necessary.

The project selection does not work:
- the service will always return the same cached image based on the repo url
- the project parameter is ignored

See example project (URL copied from Fink):
```
https://badge.inlang.com/?url=github.com/opral/monorepo&project=/Finlang/source-code/paraglide/paraglide-js-adapter-vite/example/project.inlang
```

We can close the issue until it comes up again.
