### ISSUE TITLE
[bug] Directly navigating to a locale's route 404s using the build of the static adapter—but not in dev mode.

### ISSUE THREAD

**Issue by victormihalache** [opral/monorepo#2140]
### Problem

When setting up SvelteKit's `adapter-static` using `pnpm preview` will give a 404 when navigating to a localized route (e.g.: `/it`) directly. When doing the same in `pnpm dev` it does not occur.

### Expected behavior

It should work just like in dev mode.

### Reproduction

In [this repo](https://github.com/victormihalache/inlang-adapter-static-bug-) one just needs to:

1. `pnpm i`
2. `pnpm build`
3. `pnpm dev` (for it to work)
4. Append `/it` to the route
5. `pnpm preview` (for the broken version)
6. Append `/it`, will see 404

### Other information

https://github.com/opral/monorepo/assets/82441538/9f53a52b-f032-4db3-9d50-40bc928ec610

**Comment by LorisSigrist** [comment]
It seems like the `<link rel="alternate"` links are currently broken, so the SvelteKit crawler doesn't discover the alternate language version of pages when using `adapter-static` will be fixed today!
