### ISSUE TITLE
[bug] VSCode extention doesn't expect a language code longer than two chars.

### ISSUE THREAD

**Issue by victormihalache** [opral/monorepo#2154]
### Problem

When setting a language code to `en-US` instead of `en` the VSCode extension uses newlines when it could just use a longer line.

### Expected behavior

No new line.

### Reproduction

In `project.inlang/settings.json` set a tag in `sourceLanguageTag` and/or `languageTags` to something like `en-US`. Open the Inlang extension under the "messages" section.

### Other information

<img width="322" alt="Screenshot 2024-01-30 at 16 23 34" src="https://github.com/opral/monorepo/assets/82441538/29a0119b-d7d9-4309-81c3-a33cb7be0a9c">

**Comment by victormihalache** [comment]
A sample repo where this can be seen: https://github.com/victormihalache/big-app

**Comment by felixhaeberle** [comment]
@victormihalache Thanks for reporting, I will fix this today!:)
