### ISSUE TITLE
[bug] VSCode extension doesn't work when messages are stored elsewhere.

### ISSUE THREAD

**Issue by victormihalache** [opral/monorepo#2155]
### Problem

I have the messages in the app stored elsewhere (I have a monorepo). In `project.inlang/` I've set `plugin.inlang.messageFormat` to `../../i18n/first-app/first-app.{languageTag}.json`.

This is because I have:

```
./
./apps/myApp <- Where the SvelteKit, and Inlang live
./i18n/myApp/myApp.[lang].json <- Where I host all translations
```

The code works just fine, translations are pulled in correctly (as in: `src/paraglide/messages` has all the files with all the correct translations), but the VSCode extension complains stating that "a given string was not found in the locale": I assume this is because it's not where it expects but default (don't know enough about VSCode to check what the extension actually does)

### Expected behavior

To not complain

### Reproduction

https://github.com/victormihalache/big-app

### Other information

<img width="686" alt="Screenshot 2024-01-30 at 16 41 56" src="https://github.com/opral/monorepo/assets/82441538/63617c08-992c-41a0-9223-6999b5ffec47">
<img width="675" alt="Screenshot 2024-01-30 at 16 42 21" src="https://github.com/opral/monorepo/assets/82441538/f72e86e6-f701-4958-bd3f-ff4f34e68508">

**Comment by victormihalache** [comment]
Forgot to mention: it builds, and hosting it with `http-server` and `pnpm preview` works just fine, so that's why I'm nailing it down to just the extension itself.

**Comment by victormihalache** [comment]
A sample repo where this can be seen: https://github.com/victormihalache/big-app

**Comment by victormihalache** [comment]
Seems to have fixed itself after reopening many times(?)

**Comment by felixhaeberle** [comment]
if this occurs again, feel free to reopen this issue!:)
