### ISSUE TITLE
[bug] Lighthouse: Document doesn't have a valid hreflang (Relative href value)

### ISSUE THREAD

**Issue by leoj3n** [opral/monorepo#2164]
### Problem

![image](https://github.com/opral/monorepo/assets/990216/dee6696a-09d5-4d81-a82a-600a96c3281c)

### Expected behavior

Link for hreflang should not be a relative URL.

### Reproduction

Create a Svelte app using Paraglide so that an `hreflang` is injected to `<head>` post hydration like that:

```html
<link rel="alternate" hreflang="en" href="/photos">
```

### Other information

https://stackoverflow.com/questions/28291574/are-relative-links-valid-in-link-rel-alternate-hreflang-tags

**Comment by LorisSigrist** [comment]
Thanks for pointing this out! Google does accept the partially qualified `alternate` links, but I'll still fix this for spec compliance.

**Comment by LorisSigrist** [comment]
I fixed it, but it does come with the caveat that you now need to set `kit.prerender.origin` in `svelte.config.js` when prerendering in order to get the correct URL

**Comment by leoj3n** [comment]
@LorisSigrist It looks like if you don't specify `origin` to `prerender` the `href` is like that:

```html
<link href=http://sveltekit-prerender/ rel=alternate hreflang=en>
```

Shouldn't it be just `/` instead of `http://sveltekit-prerender/ ` if not specified?

Note that according to [SvelteKit docs](https://kit.svelte.dev/docs/configuration#prerender) `http://sveltekit-prerender` is the default for `origin`.

**Comment by LorisSigrist** [comment]
That's how it was before I made the change. The `alternate` link specification wants fully qualified links, including the protocol `https(s)`. The docs already mention that you need to set `kit.prerender.origin` in order to make this possible. 

That being said the links without the protocol and origin do "work", they just aren't spec compliant. Something we might be able to do is to add a special case for `http://sveltekit-prerender/` & use relative links if that's being used

**Comment by leoj3n** [comment]
> That's how it was before I made the change. The `alternate` link specification wants fully qualified links, including the protocol `https(s)`. The docs already mention that you need to set `kit.prerender.origin` in order to make this possible.
> 
> That being said the links without the protocol and origin do "work", they just aren't spec compliant. Something we might be able to do is to add a special case for `http://sveltekit-prerender/` & use relative links if that's being used

I was just trying to be helpful sorry if I was wrong. I think u get what I was saying but do what you want.

**Comment by leoj3n** [comment]
Perhaps you can make a simplified explanation for the novice to follow.
