### ISSUE TITLE
[bug] [Paraglide SvelteKit adapter] Type error using message-functions to translate paths 

### ISSUE THREAD

**Issue by xmlking** [opral/monorepo#2217]
### Problem

I was trying out new  message-functions to translate paths feature  in `Paraglide SvelteKit adapter`

Type 'string' is not assignable to type 'Record<"de" | "en", `/${string}`> | Message<"de" | "en">'.

<img width="1595" alt="image" src="https://github.com/opral/monorepo/assets/627951/9a7f9847-4274-426d-99a3-67bacb0c1da4">

### Expected behavior

there should not have any Type error in VS Code 

### Reproduction

try above sample in VS Code.

**Comment by xmlking** [comment]
oops! I was calling it like a function, switching to property resolved it

```js
	pathnames: {
		"/about": m.about_path,
	},
```

**Comment by samuelstroschein** [comment]
@xmlking can we improve the docs to avoid this problem in the future?

**Comment by xmlking** [comment]
> @xmlking can we improve the docs to avoid this problem in the future?

@LorisSigrist

**Comment by samuelstroschein** [comment]
no no haha i tagged you @xmlking because you ran into this problem. usually, someone experiencing a problem firsthand can give a recommendation on how to avoid the problem with better DX/docs/X
