### ISSUE TITLE
[bug] Unable to edit messages with the VSCode extension

### ISSUE THREAD

**Issue by buhodev** [opral/monorepo#2219]
### Problem

I don't know if I'm doing it wrong, but I've never managed to edit messages in VSCode using the inlang.

### Expected behavior

To be able to edit messages in the inlang extension UI

### Reproduction

1. hover the `m.error_500` function
2. open command palette
3. search for 'Inlang: Edit message'
4. see error:

![image](https://github.com/opral/monorepo/assets/105121122/449a7ce9-4b38-418a-a49c-da1fbb2edfa7)

### Other information

I already tried reloading the window but the issue persists. I can't use `'Inlang: Open in editor'` either.

- OS: `Windows 11`
- VSCode Extension: `v1.32.0`
- @inlang/paraglide-js: `"1.2.5"`
- @inlang/paraglide-js-adapter-sveltekit: `"0.4.0"`
- @sveltejs/kit: `"2.5.0"`
- Inlang settings:
```json
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": ["en", "de"],
	"modules": [
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-valid-js-identifier@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js"
	],
	"plugin.inlang.messageFormat": {
		"pathPattern": "./resources/{languageTag}.json"
	}
}
```

**Comment by samuelstroschein** [comment]
@felixhaeberle is developing the ide extension and will be back from vacation tmr! i assigned him to take care of this bug

**Comment by felixhaeberle** [comment]
@buhodev Can you provide more details e.g. if you have a project_id file also in your project.inlang directory? I can't reproduce it with your setup.

@opral/team does anyone of you encountered this bug before and can possibly help me identify what's going wrong here? tested both on MacOS & on Windows and can't reproduce.

–––

EDIT: WOW – this was one of the hardest bugs I encountered so far – it seems that it is an vscode related bug

reproducible in 1.87.0 experimental
https://www.loom.com/share/ecd48a0af7154d47a503c3294d945451

not reproducible in 1.86.0
https://www.loom.com/share/0ff7c5670bb24ff88220d5299a2da6ad

**Comment by felixhaeberle** [comment]
@buhodev can you verify it's working with v1.86.0?

**Comment by buhodev** [comment]
> @buhodev can you verify it's working with v1.86.0?

What do you mean? Should I downgrade to v1.86.0? I'm working with this vscode version:

<img width="287" alt="image" src="https://github.com/opral/monorepo/assets/105121122/89caa344-709a-4971-b3e1-889555c332be">

**Comment by felixhaeberle** [comment]
@buhodev Can you possibly share more details? 
I can't reproduce it with an identical setup + vs code v1.86.1 & the extension on v1.32.0

LOOM: https://www.loom.com/share/7e7c2c2a7f6847a498169620bba7d6c8

**Comment by buhodev** [comment]
@felixhaeberle Thanks for the video! I didn't know you could hover over the message and get that overlay. I was just placing the cursor at the function, then pressing `ctrl+shift+p` to open the command palette, and then writing 'Inlang: Edit a Message' (this step throw the error dialog of `cannot destructure property 'messageId' of 'undefined'`). Doing exacly what you did in the video allowed me to edit th message 😄

**Comment by felixhaeberle** [comment]
Fine! I'll mark this issue as closed then. 
Did you see the inlang Tab in the sidebar? There, you can also edit your messages.

Can you possibly open a new issue regarding:
> but I can't edit them after they are extracted doing the same steps with the command palette

Very much appreciated!!
