### ISSUE TITLE
IDE Extentions/VS-code shows a misleading inline warning for an invalid settings.json

### ISSUE THREAD

**Issue by jannesblobel** [opral/monorepo#2222]
### Problem

If the settings.json is invalid because of a comment in the JSON and the project has a project_id, VS-Code/Kebab displays an inline warning that is misleading and incomprehensible

### Expected behavior

A warning with a clear description of the problem and that it may be the same warning as in the error window in the left corner (see below)

### Reproduction

1. fork [this repo ](https://github.com/jannesblobel/example_Opral_issue_-200_with_projectID)
2. open it in VS-Code
3. go to the `settings.json`

### Other information

OS: Mac 14.1.2
vsCode: 1.86.1
VSCode Extension: v1.32.0

#### Note🍿 🎪 
If you comment on Loom, please let me know, otherwise I won't notice.
https://www.loom.com/share/77f61ddb1567444088920b221894b087

![CleanShot 2024-02-14 at 19 57 26@2x](https://github.com/opral/monorepo/assets/72493222/fa76692a-3bbb-4a8f-aa21-ed81c73fa40b)

**Comment by jannesblobel** [comment]
If the project_id is missing, the bug does not occur. 
[see here
](https://github.com/opral/monorepo/issues/2221)

**Comment by felixhaeberle** [comment]
cc @samuelstroschein I will remove this message because people should not manually edit the settings.json and therefore the message in this file is not needed anymore & of no benefit especially because the syntax matcher isn't even required anymore with the inlang tab. #2184

**Comment by buhodev** [comment]
Not sure if this is related but I added the $schema key from the [official example](https://github.com/opral/monorepo/blob/main/inlang/source-code/paraglide/paraglide-js-adapter-sveltekit/example/messages/en.json) and this is what I get in vscode: 
<img width="561" alt="image" src="https://github.com/opral/monorepo/assets/105121122/11f39d8e-4f77-4346-92bd-21422534ef0b">
and what I get if I follow the url `inlang.com/schema/inlang-message-format`
<img width="391" alt="image" src="https://github.com/opral/monorepo/assets/105121122/21fdb9b2-dcf5-46dc-80d3-ed2cc1d344e2">
