### ISSUE TITLE
[bug] cli machine translating not found error

### ISSUE THREAD

**Issue by david-plugge** [opral/monorepo#2225]
### Problem

When executing `npx @inlang/cli  machine translate --project project.inlang` i get the following error:
![image](https://github.com/opral/monorepo/assets/59972093/05c560cf-e8aa-48a3-a808-4404e7083c13)

### Expected behavior

Translate the messages successfully

### Reproduction

Run `npx @inlang/cli  machine translate --project project.inlang` in your project

### Other information

- node `v20.11.0`
- npm `10.2.4`
- @inlang/cli `latest`

**Comment by david-plugge** [comment]
There is another issue regarding the schema url:

![image](https://github.com/opral/monorepo/assets/59972093/0e370f1a-e7ad-40dd-ab9e-5f8e29ce8abc)

**Comment by samuelstroschein** [comment]
@david-plugge is the issue resolved? our rpc server seemed to have crashed but is back up

**Comment by david-plugge** [comment]
Yes it works, thank you!

**Comment by DavideSegullo** [comment]
Hi guys I think the RPC server is down again, @samuelstroschein , I also have this 404 error, thank you!

**Comment by samuelstroschein** [comment]
@felixhaeberle can you investigate the 404 in rpc?

**Comment by felixhaeberle** [comment]
@NiklasBuchfink who resolved this bug

**Comment by DavideSegullo** [comment]
Now it's working! Thank you
