### ISSUE TITLE
logger option for the sdk

### ISSUE THREAD

**Issue by jldec** [opral/monorepo#2230]
### Problem 
It would be helpful to have logs that can be turned on and off for debugging e.g. to better understand internal behavior in the sdk. 

### Proposal
__(thanks @samuelstroschein)__
Add a logger to the sdk that can be configured with a loadProject() option like `{ debug: true }`
The option could also be exposed via a  --debug flag on the CLI

**Comment by samuelstroschein** [comment]
@jldec assigning you to make sure this issue will be resolved
