### ISSUE TITLE
Surprising re-ordering of messages in both source and target json

### ISSUE THREAD

**Issue by jldec** [opral/monorepo#2232]
### Problem
I noticed that `inlang machine translate` re-orders messages in both source and target language files.
See diffs of en.json (source language) and de.json (target language) below.

#### I would have expected 
1. the order of existing messages (in both files) to be preserved
2. the order of new translations to match the order of their non-missing counterparts (not essential but nice)
3. The schema to stay at the top always (should follow from 1, but if we do force a sort every time, let's exclude the schema)

![Screenshot 2024-02-15 at 18 02 53](https://github.com/opral/monorepo/assets/849592/83e73ee9-7da4-4e1d-911b-9182528709d2)

![Screenshot 2024-02-15 at 18 02 36](https://github.com/opral/monorepo/assets/849592/2da180b9-52db-4c9b-a7d1-3b3e7f845bd2)

**Comment by samuelstroschein** [comment]
i hate this. looking forward to semantic diffing in lix
