### ISSUE TITLE
[bug] Messages can't be edited with command palette

### ISSUE THREAD

**Issue by buhodev** [opral/monorepo#2238]
### Problem

I can't edit messages with the command palette after they are extracted.

### Expected behavior

Messages can be edited triggering the 'Inlang: Edit Message' command from the command palette

### Reproduction

1. Step your cursor on a message function (e.g. `m.500_error()`)
2. Open command palette (ctrl+shift+P)
3. Write `'Inlang: Edit Message'` in the combobox to search for that command
4. Press enter
5. See error

![image](https://github.com/opral/monorepo/assets/105121122/449a7ce9-4b38-418a-a49c-da1fbb2edfa7)

### Other information

OS: Windows

**Comment by felixhaeberle** [comment]
hey, I see what you mean. the inlang extension is not supposed to work like that.

please use either the 1.) hover editing or 2.) inlang tab to edit your messages.

1.)

<img width="378" alt="Bildschirmfoto 2024-02-16 um 12 22 23" src="https://github.com/opral/monorepo/assets/34959078/03112d07-c10d-4c5f-bef9-ce4aa76115e7">

2.)

<img width="945" alt="Bildschirmfoto 2024-02-16 um 12 22 55" src="https://github.com/opral/monorepo/assets/34959078/758c00e8-8f45-4055-a437-905f4af3f54b">

I removed the commands from the command palette in #2241
