### ISSUE TITLE
styling mechanism for shared web components

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2250]
## Context

We need to agree on a styling mechanism for #2249, #2026, and future sharable components.

### Must have 

- [ ] using the shadow dom to provide style encapsulation and being able to offer slots

### Maybe

- TODO

### Out of scope

- TODO

**Comment by NilsJacobsen** [comment]
Update on styling mechanism:
https://www.loom.com/share/35c310f573ba4b0ea33745a9748a8733?sid=f86b9d63-4bca-4190-a711-88c3f62ff6d2

TL;DR
- every component comes with its own encapsulated base styling defined by inlang tokens
- every app can now override these inlang tokens -> pretty flexible

**Comment by samuelstroschein** [comment]
**Call with @NilsJacobsen**


- colors, spacing & co should be derived. can't expose `color-50`, `color-100`, etc because an app might not be able to define colors in N steps
- use scoped CSS variables on elements to avoid global variable pollution and (accidentally) building a design system
  - makes documentation easier "this are the style variables you can set for this component". no need to explain a "check out the inlang style variable system"
- we can add variables incrementally. YES this will become ugly. BUT that will give us requirements to build a good (!) design system in X months

```html
<inlang-settings></inlang-settings>

<style>
inlang-settings {
  --primary: red
  --base-font-size: 14px 
  --secondary: blue
  --spacing-base: 40rem
  --foo: 10px
}

inlang-message-editor {
  --primary: red
  --secondary: blue
  --something: else
  --spacing-header: 10rem
}
</style>
```
