### ISSUE TITLE
fink wrong icon for sharing a link

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2266]
### Problem

![CleanShot 2024-02-20 at 10 48 12@2x](https://github.com/opral/monorepo/assets/35429197/b85ed989-8679-42bc-9ef9-c2d7d52be565)

### Reproduction

n/a

**Comment by NiklasBuchfink** [comment]
Changes:
- Link icon (for translators)
- Toast message is more precise
- ID is clickable and copies the text (for developers)

https://github.com/opral/monorepo/assets/59048346/1f6d11fd-126d-4ddd-9e4f-0e97e67970e8
