### ISSUE TITLE
[bug] SDK can't locate settings in Docker Environment

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#2281]
### Problem

From [Discord](https://discord.com/channels/897438559458430986/1210551535235239986/1210551645981900810)

The Inlang SDK fails to locate the Inlang settings file in docker environments & crashes. It likely can't find a repository root either (which should still work for reading from FS)

Example Dockerfile:
```
FROM node:lts AS base
WORKDIR /app

COPY package.json package-lock.json ./

FROM base AS build-deps
RUN npm install --production=false

FROM build-deps AS build
COPY . .
RUN npm run build

FROM base AS runtime
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

ENV HOST=0.0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs
```

![Logs](https://media.discordapp.net/attachments/1210551535235239986/1210552080847216640/image.png?ex=65eaf97b&is=65d8847b&hm=de0c3b0e0be6b17fbb5361ffcfa00a9fa7208e5f2c48142ce21a30b2b2e99924&=&format=webp&quality=lossless&width=1270&height=394)

### Expected behavior

The SDK locates the settings

### Reproduction

Read thread

### Other information

Happened when using the Paraglide Astro integration (which just defers to the Vite plugin under the hood)

**Comment by LorisSigrist** [comment]
cc @opral/inlang-sdk

**Comment by felixhaeberle** [comment]
This is likely a bug where the docker virtual file system is not correctly mounted to the real fs, causing in "files do not exist". If true, this can only be fixed in the configuration from docker & not from inlang side.
