### ISSUE TITLE
SDK `loadProject` very slow on large repos

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#2301]
## Problem 

The `loadProject` call is very slow on large repositories. 

https://github.com/opral/monorepo/assets/43482866/295822ca-0266-4a55-8bb7-f79d08d840a7

This is on the vercel/next.js repo in one of the example projects. It's slow every time

The `loadProject` call happens immediately after the "Creating new inlang project in ..." log message
 
I assume that it's taking so long because it needs to mount the virtual file system. This might be auto-fixed with the partial checkout, but I'm still going to keep it as it's own issue.
 
## Proposal
Make it not slow

**Comment by samuelstroschein** [comment]
> I assume that it's taking so long because it needs to mount the virtual file system.

`loadProject` uses node's fs in node environments. hence, there is no virtual file system in node envs.
