### ISSUE TITLE
continuous benchmark of `loadProject` startup time

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2302]
## Problem 

`loadProject` is becoming/became too slow https://github.com/opral/monorepo/issues/2301.

## Proposal

Implement a bench test for `loadProject` that is continuously tested with every change.

- decreases risk for performance regressions
- instant visibility of a startup takes too long

**Comment by samuelstroschein** [comment]
@jldec default assinged you. if you deem this to be unimportant, you can close the issue for now as not planned. 

@opral/lix you will run into the same issue with `openRepository()`. Also a good idea to implement such continuous bench testing there?

**Comment by janfjohannes** [comment]
@samuelstroschein  benchmarks will be part of the lix test suite, not sure how that would relate to lints.  currently i develp against cal.com and test performance manually before every change but in the future this will be required.

**Comment by jldec** [comment]
+1 for continuous perf benchmarks
