### ISSUE TITLE
add star button to website 

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#2316]
## Problem

Users don't star us that often because they find everything they need on https://inlang.com marketplace etc.

*We aim to be the localization solution for devs, therefore, gaining stars would be great – although this is nothing we should focus on primarily. It's only a byproduct but can be enforced with minor UX improvements.*

## Proposal

Use https://buttons.github.io/ to create a star button and place it on website.

Add the star button to website header or footer where you deem it right @NilsJacobsen or somewhere else where it would fit better with the goals of:
- gently push the CTA on starring our repo to gain more popularity among devs
- a lot of open-source repo-centric projects have such a button, potential trust level of devs higher 
- quick link to github which gets easily discovered for the eye 
- nice gimmick

<img width="1277" alt="Bildschirmfoto 2024-02-29 um 15 43 56" src="https://github.com/opral/monorepo/assets/34959078/448ae08b-eb19-45eb-957f-f97b5392db8f">

**Comment by samuelstroschein** [comment]
i pushback. the change is not worth it because it a) stars don't bring value b) will be removed again because a star us button is a CTA that distracts from more valuable CTAs. 

every product that heavily advertised "star us" removed it entirely from the site. good example is posthog.com.

**Comment by NilsJacobsen** [comment]
I maybe would go one step further and remove twitter and discord from the main nav, because nobody clicked on it in the last month. It just makes noise. 

<img width="419" alt="image" src="https://github.com/opral/monorepo/assets/58360188/ef1af41e-5528-4e9a-b6a8-391cd27b76a0">

We'll keep it on the footer and also on the error pages etc....

**Comment by NilsJacobsen** [comment]
Let's close this for now. Reopen if you disagree.
