### ISSUE TITLE
add "contribute (via Sherlock 🕵️‍♂️)" to ninja action

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#2318]
## Problem

Technical users who don't use fink can only edit their messages in fink, which is cool because it gives fink a great channel but misses out other opportunities.

## Proposal

<img width="503" alt="Bildschirmfoto 2024-02-29 um 16 43 25" src="https://github.com/opral/monorepo/assets/34959078/76c1245d-15fd-4c6e-a5f9-205a93fc764e">

---

Introduce "contribute (in Sherlock 🕵️‍♂️)" in ninja action as additional option / alternative to "Open in Fink". 

This can be easily achieved with using the `vscode://`URI and the direct link to the extension and **can even trigger the message view there**, I can even read the id and provide filter the right message.

like 

```ts
function openVSCodeExtensionView(extensionPublisher: string, extensionName: string, viewId: string, messageId: string) {
  // Construct the URI for the custom view. This format is hypothetical and will
  // depend on the extension's implementation of URI handling.
  const uri = `vscode://extensions/${extensionPublisher}.${extensionName}/view/${viewId}/message/${messageId}`;
  window.open(uri, '_blank');
}

// Example usage:
// Suppose the extension supports opening a specific view via a custom URI
openVSCodeExtensionView('inlang', 'vs-code-extension', 'messageView', 'big-gray-elephant');
```

or in markdown where we don't have the possibility to do code -> the compiled output:

```md
[contribute (in Sherlock 🕵️‍♂️)](vscode://extensions/inlang.vs-code-extension/view/messageView/message/big-gray-elephant
)
```

cc @NiklasBuchfink @samuelstroschein

**Comment by samuelstroschein** [comment]
lol love it. let the cross selling begin. but, @felixhaeberle the UX is degraded if nobody has sherlock installed and the link is broken. 

**Proposal**

Only show the button when sherlock is in the workspace recommendations to ensure workings links. 

**Additional information**

@felixhaeberle this seems like it's your task, not niklas. You want to cross-sell your app, no?

**Comment by samuelstroschein** [comment]
wait no. @felixhaeberle your link doesn't work. 

`vscode://extensions/inlang.vs-code-extension/view/messageView/message/big-gray-elephant`

1. the repo needs to be selected (how to do that. you don't know where a user cloned a repo to)
2. the correct inlang project needs to be selected (you could expose links potentially)

i don't see how you can solve 1 with links in vscode because there is no fix location of a repo on the users machine

**Comment by felixhaeberle** [comment]
@samuelstroschein don't you know we have auto-select in the extension & additional can do an argument in the link for passing the project id / project path?

**Comment by samuelstroschein** [comment]
@felixhaeberle your link doesn't work. vscode needs to open the correct codebase. auto selection of projects doesn't matter if vscode doesn't open the correct codebase

**Comment by felixhaeberle** [comment]
ouch. you are correct – this will not work because I don't know which folder is opened and there is no way to tell vs code from web which folder to open. let me check for further reference if this is truly not possible but then postpone this for now.
