### ISSUE TITLE
cross sell sherlock from fink

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2321]
## Context

Sherlock will introduce #2319, which can be used for cross selling logic. 

## Proposal 

Use #2319 to introduce a prompt in fink to cross sell sherlock. 

### Must have 

- [ ] good UX ! (no annoying popup, a message that makes sense on why sherlock should be added)
- [ ] if user rejects, store the rejection in local storage and not prompt again for X time (ensure good UX!)

**Comment by NiklasBuchfink** [comment]
I close this because the Fink user is probably not the target audience of Sherlock and will not decide on the developer tooling. Other apps are better suited to recommend the use of Sherlock to developers.
