### ISSUE TITLE
`@inlang/cross-sell-ninja` package

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2322]
## Proposal

Enable apps to cross-sell ninja with a package that exports two functions: 

1. `isAdopted(args)` - checks if a github workflow file contains ninja/can be used to show a prompt to a user
2. `add(args)` - adds a ninja github action to the repo

```ts
import { isAdopted, add } from "@inlang/cross-sell-ninja"

// check if ninja is adopted (a github workflow file contains ninja)
if (await isAdopted(fs) === false){
   // prompt the user
   const response = await showPrompt()
   if (response === true){
     // add ninja
     await add(fs)
   }
} 

```

### Additional information 

- i recommend to create the package in `inlang/source-code/cross-sell/ninja`

### Requirements

- [ ] code is isomorphic (works in browser and node)
- [ ] returns `isAdopted() === true` if no github action is found (don't add github actions if users use gitlab etc)

### Follow up tasks

- [x] opral/inlang-sherlock#6
- [ ] opral/inlang-paraglide-js#31

**Comment by felixhaeberle** [comment]
@NiklasBuchfink can you provide an ETA for this? I want to start cross-selling Ninja as early as possible in the VS code extension

**Comment by NiklasBuchfink** [comment]
Thank you @felixhaeberle for your help. This package has now been tested, merged and can be used by apps.
Happy Easter 🐰
