### ISSUE TITLE
Sentry error logging for sdk

### ISSUE THREAD

**Issue by jldec** [opral/monorepo#2333]
## Problem 
The sdk should be able report unexpected internal errors which may occur during operation of sdk-based apps.

## Proposal
Integrate the sdk with sentry.

**Comment by jldec** [comment]
This would be extra useful as we roll out #2108 and related PRs.

**Comment by samuelstroschein** [comment]
@jldec you could also use sentry for performance logging (given that we figured out that some things are too slow now)

**Comment by jldec** [comment]
Closed in favor of https://linear.app/opral/issue/MESDK-60/sentry-logging-for-errors-and-performance
