### ISSUE TITLE
improve sherlock appearance in vscode

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#2341]
## Proposal

- [x] thicker logo vector line in sidebar menu
- [x] on hover, display "Sherlock", not "inlang"

cc @NilsJacobsen I take over 2

**Comment by NilsJacobsen** [comment]
thicker logo -> https://github.com/opral/monorepo/commit/7237560b374363fa237f55ca1d77e6e2c43d8cce

**Comment by felixhaeberle** [comment]
this is going to be merged Monday
