### ISSUE TITLE
[bug] Paraglide error parsing Svelte 5 {@render} syntax

### ISSUE THREAD

**Issue by yookers** [opral/monorepo#2348]
### Problem

Trying to import components that contain the new `{@render children()}` syntax used in place of `<slot />` in Svelte 5 causes it to error during parsing. It works fine if I remove the new render syntax and use `<slot />` instead.

`ParseError: Error while preprocessing C:/../Component.svelte - Unexpected character '@'`

Removing the paraglide plugin from `vite.config.ts` fixes the issue, so I'm assuming it has to do with it parsing incorrectly.

```ts
export default defineConfig({
	plugins: [
		// Removing this makes it work.
		paraglide({
			project: './project.inlang',
			outdir: './src/paraglide'
		}),
		sveltekit()
	]
});
```

### Expected behavior

It should work with `{@render children()}` as that is the replacement for `<slot />` in Svelte 5.

### Reproduction

1. Do a fresh install of SvelteKit via `pnpm create svelte@latest project`
2. Run `pnpm dlx @inlang/paraglide-js init` and install the Paraglide Vite plugin `@inlang/paraglide-js-adapter-sveltekit`.
3. Add the adapter to `vite.config.ts` and initialize the `i18n.ts` following all the steps outlined in the SvelteKit guide.
4. Create a new component and use the new `{@render children()}` syntax, then import that into the root `+page.svelte` file.
5. Running the dev server or trying to build results in an error `Unexpected character '@'`.

The exact code for the component:
```js
<script lang="ts">
	import type { Snippet } from 'svelte';

	let { children, ...props } = $props<{
		children: Snippet;
		[key: string]: unknown;
	}>();
</script>

<button {...props}>
	{@render children()}
</button>
```

**Comment by LorisSigrist** [comment]
It's probably using the Svelte 4 compiler to try and compile the svelte 5 code. I'll try to update it so that it uses whatever svelte version is used in the current project.

**Comment by LorisSigrist** [comment]
Jup, was that. I'll turn the adapter's dependency on `svelte` into a `peerDependency`. 

If you are using `pnpm` you can immediately fix your issue by adding the following to your `package.json`
```json
 "pnpm": {
    "overrides": {
      "svelte": "$svelte"
    }
},
```
This will force any package in your dependency graph to use _your_ version of svelte

**Comment by yookers** [comment]
I tried using the pnpm override fix in `package.json` but it didn't work. I was playing around with it some more and it seems like it's actually `{...props}` that is affecting it. I can actually use `{@render children()}` normally but as soon as I pass in `{...props}`, it gives the error `ParseError: Unexpected character '@'`.

```svelte
// This fails.
<script lang="ts">
	import type { Snippet } from 'svelte';

	let { children, ...props } = $props<{
		children: Snippet;
	}>();
</script>

<button {...props}>
	{@render children()}
</button>
```

```svelte
// This works.
<script lang="ts">
	import type { Snippet } from 'svelte';

	let { children, ...props } = $props<{
		children: Snippet;
	}>();
</script>

<button>
	{@render children()}
</button>
```

**Comment by LorisSigrist** [comment]
This code is working perfectly fine for me. Do you have a repo I could take a look at?
<img width="428" alt="Screenshot 2024-03-08 at 12 58 07" src="https://github.com/opral/monorepo/assets/43482866/aac4db2d-298c-4b89-831f-d938232f35c0">

**Comment by yookers** [comment]
I made an example SvelteLab environment, it will work if you remove `{...props}` or you remove `paraglide({})` inside of `vite.config.js` plugins:

[SvelteLab Env](https://www.sveltelab.dev/?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte%2C.%2Fsrc%2Froutes%2FComponent.svelte%2C.%2Fsrc%2Froutes%2F%2Bpage.server.js%2C.%2Fpackage.json%2C.%2Fvite.config.js%2C.%2Fsrc%2Flib%2Fi18n.ts%2C.%2Fproject.inlang%2Fsettings.json%2C.%2Fsvelte.config.js%2C.%2Fsrc%2Flib%2Findex.js%2C.%2Fsrc%2Fapp.html%2C.%2Fsrc%2Froutes%2F%2Blayout.svelte%2C.%2Fpackage-lock.json#code=N4IgdADgTgpgLnAljKiDmA7A9rEAuUAM0QBsZ9QBjLDOGWgZwpAGtEMATfEBgNxhJ0SAQwBGAWgCuiABzCQAGhCjJhQinwBtACwA2BbpkKZAZgUBOAKzGzARlv77thfe0uADM9vuX331-cfb2crD3N-DyDbAHYPI2Dfaz9tWPN4mI8k93jAjwUU-MdbJNscgPTHT3ys2O8Syvza2wAmC1Tw71Ta9zsq5MqvP3scwo9BqKM9fNa-EzMphPsJ0cXmn3Nujpa4sbzZ6xNW6N67IftfNwTDjxn3LLLEhWvvGfPXJ9aZH2ijL4Vo2LaNzXH7Gb6xa4bXxBXLXGThXTWGRHEb2V5RW7hbT3CLmDruQGOZohTY7M6tKF4jxdDy9ZzYsnnKmdFbuIolcZ7YltC7Q1npEL47oAXQAvuKlJBYAhkFAoJRmMQyMxqLR6HAmARWOwuHgePxBAIxFJZPIlCo1Bo8JoWr0LE9Lhl7FlnDI3JT0gc3JYjM8HLz7N16Zd1g7HnU%2Bd5eg8ZIMmoMBmGfR9fEVHUH8iH7SZHWmeRHvDkSjCzLp42EK1Ccwpk9dq0sIg2rm4gXlwvXtu8C2d9DJulkopVgd7fa1tFjJpMs%2B3Hbd0t1esXHtXaxTnB3XiGE6nMrt3gy0YyF7uGwfir4HoWd82LPNp2GnBe97ZHSGB8%2BvTXRxYvM0zHWQ1uHFFnPFdv2rbQx3ZJ9Fmya8qgg4FWg7QZXkqDlI1AkcU1tFMN3zF9wz6QiwLwx0SkvOD7ETatnmaA4Zno28uSyMUJRACBhEoFhhDQGAwAAKwYGhFVIcgtVVOhGGYNhOG4PgBCEY1pDkRRlFUdQoC0XC-BnPkoW8fF12wgD81yYZn0HapG3cMcSgovcqP9BIz3TSNiM-VtdIfUpn3Ik83lmEzkJbSZ9G0ML8j0rzQ3wrs7ifAznIQ4Lr0IwNdhi7N-OZdKEsPajl1SnTQz07wYUGX1Uo7It4PXW4KqfRC22yix5xPKjYWqx1asKq4KXagtOp8ZrvLKzs8sqjrBj01cfN65L6t8Tdn164jovvMrOqXQrSNMgrJrS9C-JTBkGWZdwtwsIVTv0UbSofWzGzy8Ikru7rloDYiimOkCkOss8tjfOrbse%2B0WmsLKtsaizDGfW5OXKyzrumoqvxwv8Wr03RgabOCkpLRpPqS91jyvIbGoPNk0bmiCsX0SwfCmSxPM2sMcYCmEjAJ2kicPEmzOjDrKayaDzu6dYmjQk6zwc2CKkc-sdz2kKLFC0ZLHmBn-xbNnqw550YL6JzE28MWaSRpLpb%2B6ykqaIpjPR0zzG9elwsiiKwyh1qDfPCz5ZBs3HgKFlu3ep3VZdmsmfd0ZPfu%2B1sf8-3jYV2DzaN%2BpMpKOdfDJ-Lknso3yhBlWwyjyw3fyD2qszLGfJWkCftR94y%2BrCuq89qZ491%2Bu4sOvrkpdXkz1zjKo056zDZTku%2BpSiPy9duOa69vXk98gO58d2n3W9LXq%2BXqehj6NYd27ja%2B56gKaI%2Biv9672P61DCG6%2B8lDi4DPL3xAz85pKxP2br0omnY2GdQ4F3Dn-TGY1Wrj2PjCawF1f7gT3hrHwjM45bQAS-byL9vYdiJKhXYbcQxbACFEboDwE7Q3hsjJGIF1j4mHobMu-9XqAJuM9Ky09ApNHdEZPm7gyF50wvoAyBcoiQwwi8W2%2BJXwBSzoZAiyCyJqxrPfD24QWar0vuGDeqcQbnTkbsC6EJb5L2Zi2BmI17w4KCPRNioolDQCwAJGAlA4BgHYCIDAaBmAcEQLADxOAACezAGDwCQL4hgglhIYFEsqCSNApIahkjqeSBolISBUmadSlotLWn-nWVWJhoIXSukoqsH1vC5jSq8awyYCghwkTsHmE8pi5QCFiJoiDjGwVeoCKWn8AiJlyuFIuTd4I7R6GjLKxSfLSKdIRC6zhohiKaITDK4i6TGFJrzEhyME7zKftzDZvMtn51dHsieLDUrmACHhZCTzHqcifo85icznlP2EfQp0nVBgqMhA845XyQy1MHvU9GTT2iRD5Asam09zIGO7OkKx7ltwh3JBWAoBsWlXjaTM5pAieGIMuVPbaoij5uXJlUKmXTPp9W5KPAizcbYNlxacwOft-TNIQXo8KSs8Yw1PvC6CRyvmgo8OC5yE0GmTEGSjX5McPDQXociguqKVjHwxWcgqQiia4umZyvG8xSQ-0eNs7OZI8U8pKNS-55Lv7EW4QlKk4jJg5xZVyx0PgOVevNYVXlCiz6CvgXuEVlQxW91mBK1RNSjoMvPI0hVF0ojKqDoimGFL-aEQWNqkNmFMQGtxsfY1x9TUVgDeeS1LlgI2vGZ-ShVqlHdgmXiwlijlm6r9vje2AVOR%2Breh%2BAtaqJk8tDTCYV6aEVYVfiNWN%2B1LoJoOnKomBRU1wsjURLNC1NV5phuOwt2LYiGvcmWwmRLh2GxrbSutO1bWNutfSEoTD4KOjjGfMdH73grIMCGMtptuUCtha2kd7ap2sijXO95xywXLtlVClN%2BI02Qe3Y5XdI8igHuA02Ts%2BqcUlq5gRC9ZqPIWrJVTBaVlXIiJpc%2BxKTaKbkrFlkJ1iMh6cKGoMNwg6%2B1Vpw0isdAnpkQdFbMrMIK41LsHkUSFyaiYbtPFuzN6GAp7qw8%2BHDWKlEEcnvi3VhKhnkz%2BYuOFWRiXctJec29nHAqkK9bxrlWcg2gcDROkDJ9p1Qc%2BTB1W8aZOJtXdCxV5l%2BgqrQ5vDVmH0Uju0-hk9hHWkGYrXqwaMzuxM3M%2BS14Zyxn9rM5WPt5STqOa3vywRfKeHCfcqJ5Ts6Y0pnMHePIsGGVOXzkueFRriO83hRZouN7VlRG44V5WxVoHzt8w3f1S6-hDrK12IKC8IICf6%2BR6zAK%2BYTfPecjIg3dmCxcExMTPDXkSeeXYo7lhHHsQYPKfxgT3FwFCcwYQEAIBgAABZwAALYkASeJKgyT1SalALJXU%2BpFJGmyaaNSFpNJaF0CNXow3FXOW5Hqpa-nkr4iMLoW4BgYTgv1VeZ4vb3Klkdgw9mBOERE5MRLAwtP7RI8rd9HkkJjEC0RduXQVOlmVDsjWcO1wcXM7p9a6ZEJG4GL549XpXCwxk-kbBVocvaI9I-sZ02BJr6jCSm27cLCFUyKSrVTpm7E2E1omOE94vCds%2B3FWdEZkBHq6vlx3wWxXgjd2v9C3uHANWXd174Wb6DDkNWruX9gMw9z17mT6ZijXVNtlijd1uw5fjiV7bpnfdNcz0ZDr0N4UhwM9hSYboLOmbdCuuI31zPWdpBsvYrHuQh1QjT4X7Xis9fMvirPJkjOqaSx3FCEP2Opo231vb1no6mqQsZbPKoE-BN6NzgZbkc0A89joTKz8%2BOngF-0YP4vfexEChA9ySvDuXNRcP95Vn67L-0O5A-31NepXwVx3n7wjilAkCICiAPZBLPZQBhJaiIClAYBgCpJahKiA4gCSQg5pJyR6gKSGgiAw6qTmgaRWg2j5Qk4TS%2B7%2Bh0T-gUhAzl5lbHBRTC58h0QMS2bvoVimSnp4w7btJDICw3prQizhaGziywpWzepHxyzIqLTUh65vJDTe7PS1Ki7PIG44TpRLIupZb9RME2TtiqzdxaYUh8KHY0psZ8wqHdq-Qk60p1afjHzhoYhyHKwUGK5VY4QJTZ6WAabXDq6OED4zarLzBaIabaBRDUq74yGZTOCWDmD-4gA6gwAAAesSAOKowO0kWo4OGSUOWBJoOBeSCO1owWfoG%2BMKGhMiQ0l4oEjEgwH6foAylKfoDsLh6hxBn8d01s0mKh366WS69RX%2BGh5gd0lQ5u3MrRZk5umuie9BbRJajBpRbww0MslQN2TiHEwgUAvEgBHAiBASoBL2WoYAaAiASAmAOAiBCByRaoqRYO6S6BmS0O2RuS8O%2BBJgMxhBpwqOPhZOU%2BxElwGOyUiWE8kIDwbqTQBeCEUxxCDUAUdeWwDRXY1%2BQEy4%2BhtGMq9GNyzqJ082xsk2zeLQbe3WBK5BxMBhPBceNmGaPaTwLxPuvIZOPyh0ExeM1JfoC0rGDhvRMqsmjw8mzS%2BJyW%2BuPy8Wx6G2n8V0lcNYK0mKSJP6%2BcvBzaM6WQ0wHg0RUokSso6A2AuA8BYk5xKSoO2oaBkOmByksOuB%2BSWgzxjRu27x9JCMWu6UvxZeGW%2ByA0JitRcCw8PR-mYJHmdqrpaUvu8JwakIIJ-p5KOyeMI2mJkegJR2eJZ6PWAJrwUpXa1mspta-BFJFpZO1JrcRaj4HxCJjJEQzJwaYcLh0qnJhs3J7m%2BmFO-JWhgi3Swpi2opEREpXBxJMppJqJ8peQkESp4oyxP2MADADAvEI5iRWpiSQOFxcBVxBpGBWS9xcOeBBSBBa6F2ZGRhlKI%2BwaHoT6p0uex8TROZKhIxuEZOHB6We2ZKboh2DBLhjccx2hXsWmIRahjuqGtyewMIA57EUAkgtAiAw5k5RA2pSSs5ep6RNxmRxpORjxa5yQgIm5m225ge5KlW1aqQOQVCY4R5n%2B-Z-Znh4KvxtpZB%2BQTMVklqc0iIDGHUnKOJDqayCZ15FsXRVyh22gS0cuh%2BJZ%2BZhBTMWOzQ-0cCk6jkhZ%2Bar%2BjBhF0uP55RIxoQ%2BZfgpgmm-w6ydZFywpd5N6fZyFipDWRFnwcGJRE0zBGaVQeWJgWwMx3K36yyAil5LFpwbFOyPRlq8Kh5LhnlxFthrubWlE3lsaQ0zyQRMW9gP%2BuJNgqmCQeWsE3w6lJqIi%2B22lx4nhzgPFWOtlyJ-CuwzFBJSVt51yhKv4doChU28yBRkJj4fo1pjp7ahJShnp0m3pp22VIWbeV5zlhhLV-olqDJFR4eJRSKAQyZjGpBRRGlN5zZk2hl5VMuRuSyPqLWeFU2l2ZVzSvlB0JBCldJkibJrVcCOVCQeVfJmlaJHFfVauS0T8Z2P5G5%2BlM1zyd5XpmVT5Iyfpu01ljWTQxqhBDFOFEJSWk1LlgNhUNa54HlZVZOgVf6vl4ishdGXlUNQVhBIVo%2BFk4iOI%2B5iNJ1wN3VF1ZMENv0ukEVfyB6kMFCREI2KlkWgogcuQuNiVZ17FB27l3F6VHNj5oxVN%2BQJVy1ipkm8y8ewyoeNVz4L5uglBi2I2oV1YjN5aBVwpblqVLuSlClP1ZkWN2FB5EEwKK1kma1K1G1qwdhSl8h3hgUe1u0yZv1WtbUB58tmyU151rNhNjBXh91s1vshCbWQlZgO%2BVt6O0lueou6wVO6J7c8wDySFip-ZBlzy0QAQ24TVV0nObVPh6Fjl%2BVzNrl0s7lDQyN-NXtFSp88N-ljkMNQtqNp0RG2dztLNKVvWglKYGVEeUmjUutR2pV%2BtC6ihu1eiy%2BVcxmAQ8wNi-wSdX0bpQwgZwlQQkRLgFpDg4Qs9Lg89tgi90QY9XFRdvdV2Lhg%2BHphZT0odQNTN9dOyjd7SzdaVbdHtHYRGndRSPdc1aO7G0iDq8KL%2BhKY9oIkyL1X0V5e11wK9xQHQG9y9oVoDC9SQAIXsetAtQVTE8dSNz93tsZvtGMo9vNLd6VzytFGNgq5OjFDwjtu2INCQl96WSDj1gim1zRi255Dq1tp9CtOduwlDhJHtoV29N9vFi%2BvCvIv6pDNy597DRVdoMdhFBOhdNN7OKdoN5OZ95DPVCVhKBdz9yDPlJtflqWCjMNmjsalVIW1yrD9VyhDRWdp1ojQ1ldF2Pa24wjrF%2BNrtTdLy9BLY8Ds1Bj7yRj-Mx%2BrJiVwZLh4ZHJJ02ZyJjCUyiuQTxmGENR9hocRNKDCDPjCq0NhdFVaTSJZOITrK3xXNolaOxNryElNloJI1tGcE4TZtyhFSWVxmVGzpHOE1SjzjytTT3jmTRMfoJTg1PVzCKh5RIltgfS%2BTQ1XxAZmVdTXV-G5Zyi31LhlWT0pRYz6JzDtZrT%2B27TaJtjyhAz%2BgjjXVyV4jFFpzPDV1ee5FnTu9GdMqBhDYfo0zlTqFPKgxTlBEhV3VuzD55zO9fzWj2w3BpI5F%2BDvkmNQNxDuVCVrD1jVQHDGM-03D19FzfDBgDk4LtZkLx10LTtyjBNvWv4Nlqj3dsdVe2jW1LRjW-dzhfo%2Bzal7zbDFDJzN9J9YNx4vzPFF2E24M1drL6ORCIEFT2zMyvDnNi6OW%2BkMJ%2BWDzHjmD9cGzMLeLLjiZbdnx7kp5R1VQhzitLt8LkDvV7LDyHQTEarsToN3L7CCruLzj8LLLtpRZNTQjOLZDNrJzSL2DvDdjxL2DuC1D9oRjwJ1q34wtfRbpnU3MDFN01TqhRT0rDWwVlp6zS6jVLpsEvTaqFTTpcVLUCbJ9illtUVky2rjLcLzLyElOqrErQq4lemWJHrjEdo7C%2BbnIsjDjzrIjSrertdVjnbbrzd29vrCpl2kjK13jfYgjRmA1PMfoZhj6zh2b0buWUr3YvTBKk21OsxkZa28jQ6-V55A8dzn8QD2TLTirbTed7L6jKTvsyZRVL5uE3D7Nlzau6LhD-1Dt7bTjxzhhJrVbZwVmKzqyn7RznzOlhdvsdTRQ9z-7crj7ODz7aLdFZRPIWLWrwHOrDdJzhtpLP5f7kTc8iy67azyzdm7V9LddvbnFlNuGAHyzaHDLsL%2BL7SftObB7UHR7Nd9bt9XLjbic1LQG5j95FzM7mEtHtpxbjHyr39PrD0CbstpmhsoLttELAN2LDHlH7lVFhrXHbC2CfxIt4VyhB6EtUtHRI86wbzFHrrVHOna%2BSqTwUrjzqlh1kxzTSH2asIp71rWzF7vWIxZYvRFlUblRz0BhtLqlEnGnKt6ejG%2BM4URr4MfrlrbH6d8bBr1miXQ7frI7D1MNrb%2B1%2BnfRsJyluT5HPb1nmn2D-RVL3N%2BKkbkhi7krUTSl06nlY7xlLVJHS7zXBbad07qbPV5TFe1s5wnpX81mIT-uEVhB7GDaiKxh4XTG6ZqunGQXaUNlJQxR3RyZLx%2Bj%2Bq4iNZIrJ7YVIztTz4MzW541oZ8jJlAzHu%2BT8TZZ8aN3g3bW6NEhSMljeNPnY%2B7LIlNDPTNJ81VKdCw1X00yhJIb3pMg1gNBgPDz4Jobkue%2BIxoVKlfwtFMTE0kK29UwVde3MNDInhL%2Bswjnf7h9fTRcjXDYsVBc6bvXiP-TJ03eJEY4yO2DkNz98yz143aJk3tbDVsl83HmPZmbdHdNSbVPp5RGkVInPOtmTa8PaXdVS0F0a0s3jWQJU9Q3QTi3YzJ%2BI8baxh1z%2B9mEC0Zlx8FmVkZO7xl3I0ZPYVdbY3UzzaB7Yl0%2BjPS0MP-w%2B86TXPNzAPQucIHXqvxXPg%2BXhUkXFX7Lzd1XfXsXEbKHwXMXrnLXZIgZjFbeWaElWa67Bbv6zvCzOaAQ74cvklp8mOsbC7A3AQJjC0MtV7XjgfsN2jZdujsE3zueBQDJx9IXSlQvSyFPWbijCthRBEWHHnHd0vgn-9evJBQzdctJZkGYi3i1ejGTIVWT13qtgUO1tXVTFIYfhb7OUf37lX29cf0-L3mVd3dp52KTVdWQaNwaEfgzYTKLYrtwUpTkw8vzT9D-NzAtq-wObocS2THaTvq29YctcGcrE3oLU37dM2etmEbKa1Lpmo8MDwP-vt26Ar9juEZUWsD3sAXcXm%2B7Cxp72SazV4BqTRATzUWwL9HuECL-Nf2UJGZ28fGJ3l5xdY-c2WGXDfi-QYEiZno9MRkHTUxKEdWQKuY2Hg1D7dMiQpwb1ngghByDQ8w-a0sIOHop8COiuPNMmUdK6RSMhLCwI313pC1jsnjG5n6zKreMb24-PyuRUgYj9vOoHY8DRVfb0UUOqnejlZzP7adPWyhL%2Bt-F-a2Zfy61Mlp5kTTbUauafGltP2AFldvuzgpplwxhAu5oBCHXTs2z5BxDT%2BiQlVh7VmK-lh2BFUds3wC7-1TEibXvgPU-JQ8IeibKdmcix7KdMWngjqup3Pa-c-O-zaRqgxLro0iCY8Y2DDVfQyJWWBcawEp01oqcP27Qnwa4z8YTtK0STDQYG0Rq48WO3jZLnSxyFaU%2B2RJRYS2mWFORRBsXekOYMax71TWP-c1iS1mpbCIuoAyTl2zcYysZOwwvet42sGzhbBZdcim0gxxBDahGlUoZIIWrQdj2XdSnnWX6ru03ByHbGkxUeFRdzklgo2mEN-Cm1SOSbPDlXzp6p9xhiHAhu4IREkMkR0feYYVzMZ-8LWX0MERxyaFTCWhMw7wbkOvKQxia%2BHdrCL2Dgup-ixVFiHdSMZnQpEAMEUcH2MDhAMekowksKNFFyibCTSEoTDUx6cCO2HQngSq2Fq7tSmRfMFm%2Bw8E60c%2BM-Zqq9QM4Io1ugaYwRQLwZ9CdGGAiunwLn47gdhurPYbc2IHlZP6sw1kYL0RKEi9RxI7WjjTJFzDmO3Q8MWg0iqV8M2nCK5vywwb8VFCGtDFkQ1aHxDNmPoi1OxlJCZ9BGdgIIZMJTHvtgx3o3YV81CF-lBySgKAFgEkB0A9S2xJ7LsVAAABqEQCElrGeJFypxcCjOV1KoEIc3YrIjkhXJmlrQc%2BatFLQLjSx38L9RGus0xhp0vSdaYIockYju1rqlZMziujOYPIn8muXKCWhnEE4-Ac%2BOzr5CXEj8i4IeYQoeBnz81JMZ4sNkuFnFUCqBZ4zCnjiMqBcpeQZPMoGQ2a-E7Ke-aIR913z7ifST4V8SYN3ofi1Mv%2BSbG%2BMQalhQRNWd-sY3cG-I6mlFH1qiP4GxoIJ8%2BWGD0KmyETsBk8WcWRM-FM5oiLYziHxDAARIoA-AKAKBRABnEIK-YtItcUNJLkRxppPIgQQxERDKWWPJIL8UibU8SaPXdNscLMg4TqRvHW5ux0WzrsaRxrCegLDmgYJPYGCMUoOxrD4gPh7gWifRP4jdikinElAtxIXK3FhxJpXIvgQnEK54onqJNp1VVbSoD8zOMIhSwYYphnql3fQGUOfIiT8BmdL-maJfJWU44J6csIcOn4btXmeiYBKXCMkjCBhCTK7kvgwbkU4QbxAKEmVUoPlo2ZlfVHWC%2Brd4TYxCLROlIPILiGqozFcbSNT4FjNxiaC3pCjnzqSMJyHLCcjDmg01jyiae1kHTzxwc16H%2BEwi5N54TRgpJ4qaZUncyziJcgUkgQYHimZTohazK7tzhTzkpixsufnIBizj3i34m5XGIhLwaf41p5WEKfSj8mSVwJBOMic%2BL5D45oiAAYSwA-YIANAdUIxNuKWS%2Bx1k%2BcoOLslwUHiq5RHHtUPGFT9qjg3mBPn3w04c2hBBGliOynxjK%2BeUz4AVO7BFTJkJUyKdLRYLIRKpBvHvFcFql3VpuydBtlEOarNTbmTMRFqXi1RvVAsGMDcXhC3GdTHg3U3jq9CanWpVx1OQafjOnEJj-Qk0gBPckkKrAIiwbATq5LrJNYF4hTRJmoL5CyzjWEwpAdvVlmETJx4PRNPNLupN5BooTNPvYPZk6CDOCGF%2BCtMhEQdQeB6Kbj%2BNFktTTwzdS7BBJxIC5Qy7KW4EsVuxwBhASABUFqEbHBJwCioYQLwEQCqhIAviYGUgRSJzl9S4M2CtgShljjNAf4DoPLNKCSjvgRgROgvTyDNAGgPgWuZXJoLRA1cvwVoHXJ8CFyXAxc%2BEAoFbkKB25IzLwF3MmDdzh5fKbRH3M7kIg3APczbMiHHoGB9AbcmKf3JcBdzx5A85ekYDXkrzwgdc6wFvJLk%2B8DAeOJED8UXlFz15vcpeRPOYj7yu5SiW%2BQERcC9hEEowB%2BUfkvnnzt5H8juRfLflvywWauA5t8OEFzB35b8twH-Kvm-yoFX8t%2Bc3mBDfzl5B8uEL3KeBmBhKT8-IIh3cKILr5kCz%2BQfL-kV9tE48HEhzDfkmBN5MC5BSPVwXQKCFd85etQq7khSIFzCiXPgp-lfz56nCpBV3MblGC6FsC9hUIoPlXg35lgNhQwqYXSLWQtwWIJItEWryRFUwXhdfPVlqKL5NKdBSIvAXKpiQHQTWEopkVcKD5KlOGG-NBBvzgpe83RSIurD-yMFxIRwKAuJC1BSkxi1%2BXYtkX-z0qpwTxRIruj-BIoMgMRAEu8WmLlFsi6rs0FeC9BWgcChJQkoiV8KIq8S8JeEuiUE5iQQQbPJFTFJ-BNFX8jxS0H0DWKTFqSmsM4DWDxBVFIiywPcyejgL4gsS8LP-KoWyK-ARSwhTop8XQJcUmSyJRUrwW6KMcAy0pS4FiCWKplIi6rv2Tfmryz5QywZZUu0BmAjFXSlRZ6E8XRAJhQQO6DMp8UiLDwvi0qhYCWWrKOlyylcOEArlECV5aif%2BVIuWWexulLCoIL0uWV-y%2BgYpN5cMq0VnlPFIzWoM0BGB-gggMgeIJCpWXXzHQdgbmM8sqVTVHFiKkZbIsUUULHYHiihUdiOBlKUl18soXBAoXJKjlsi1sNXOMCeLvefy0PJYvzHoIDAn0DBfctpXbB-5-yr%2BZLSBW2LZFwDERRXJoItARosQTer3OkygKTA4fXsPivRXoIrllS%2Bes3ijgSKQgMwWVV8uOXVKBV6VVFRfIOY5BDlyy88BIr1XCLOl2EWlbsphX0LNVsi6IB0Duj2IJhNYM1T0rJXLLOVB8wVZDAVVoq7VLyveX6ovnVdyFuivHL3OQhGrKlUq8PG6qiUBrVl8ar1QmsqXTKD4rK0lcaqqC8rllsDK1YxAuX%2Bq01qQT5ZUvHZuLV62qj1WmqLW-zl6Ka5erEFjBAqMFoConmUuDXmrjVWaypQouTU2rilZa6%2BdjgZibzOQxIGYGsoMBmAHVR2OtV-IrnWLagUcBwAurEXDqtFuuWlTuuOVdrvVjazxRaX-nUwHFWyg%2BOAs3Xdq019S25RqpvWdKr1B87euAujXFr31v89damo-VfyZEu6i9QSttUPq81CSnjHvOrWerc1wGvtfusHkDrzAva6%2BaEuMC1BOE06gtYZMw1wLYNj89sG%2Bovlfqd5T4XdT4r6DHrZl%2BG69dfLoheAq5gGqjVopxIeKK4Iov9fRvdWJqR1EISjRxrTW-BCNl8j5TMF-ozJrFUGvBa9FqQ0E-gcdXyAsvYQFBaVL69jd%2BqA0-reNsKnjSwqRB2B9KmMEjdcpPTrAn1qmr%2BYUpU1Ea5c4iizQrP9AYK51kCwdRpoI1AqcJkqgdSet7l44IN0G6%2BRit0V1w7y3IaxTxgZjGsTNr0IkAdl0D3r1Nd82Lb-NdACbr8ka4TclpUWIaL55mnxQOosW6L0tNa2FQVpeVq4nNd8t-tnhUo345lrwVzQJo5hiq2VzQLTYYrK2SiHkKW2NbSvsTeg4MOCgzZUvMBb0Wtra-4OuOHlKJstkGoFYpX617IGl%2BQCLTNqSC0U2VxKmzZYra1AqylQwFtRMu5W%2BgjsZSzLb%2BtO7prrVwW3RcFKW2%2BLxNam%2B7Qxse3ObuFPmuLZKJG3EgvAeS3mB9vsUKlT4A2wlTCAS2wLfthWh7WYqxDiT5gd20HVtrs26LYdYi5rZXMB0Q7TNB6rbdnjB2cbP1dgDmEjq7kDqQVvqHHWmv%2BCYaFtCynDVhq1U06-5U8zxc0hDAg7ntbO8rYeu%2BXiTJRCsenRtps3IbaV5GzpXvOky-Lw1ni%2BxKzox0y7D1YqhzQLoE3wLhmX1bDfOui29zdVYjAJV-lfVba8tfKwnZzpEXcqX4tKnBQrvB2-q%2BgQK07g-ghoQrbdECmnecBPUjaztWqpbXLkc1-y-YQW9KIbK22OKIiAmjKNYpp2hUalLgM8K2qW3yy21wILXbPP5VW6xFBkcXZ0sIixKvt4fYrasoE2%2BhRVosIPfUp%2BJuAW1OKywMhFJ0l70VFbP%2BYevQ3HL2wxuvlXLte0XzmK98%2Bxa3tx2nbvQ0uoubXuNUI7U9d8pbR5rKWa7HA3u3RR5uOU67sV-OuvfDqN1PA0F9oWlTEo71PbZdky8VZ4t0D%2B0TtZitfb7rBA7L8Q6C8yHvvxRLaTAO%2BsRevS20XabNE8eTRTuhXLqqV8ac3Y-r32exD8AmnhVqo83u7-9tyiA4frz1Iaz9b%2BuCBsqXTNL6WS%2BvlZ4uTAZBkNKe41b6FD1OLjlFIGA-qsH0O4lNl89xR8vp2uhPFOJSlZYth4kGl1xyifQzBIPNBOdh62fWgaP2CK0dxSqA-5s6X6aTdSQXvb5vR0bzxVYDOudjrJ14L59Y%2BsQ7CpP38K95oKyZVCviAjbY1kVIkG3KgOfan5HmqiHvr4Ps7OdBwNfdasiqwND8Gi-KCAdkWs44FChl5QEoxw4LuV4Cg1TQaUMSGDsFCr3R0A7kOdh9qym7cvs9WOreQDWoFZvOQgIqwjI674BEcUNHYB1MUvnWkZ3VwHSNtQALrdtt0Cb1lWRvveYapV67QgtKqzXJsiPiHhFW27A0ityBmGiddKuo9fI%2B1i7Sj9R8o2JqSP%2BHHFq6OXYvK21dyENvMP%2BeAZ6Nvang9OkbUYrWB2Ax5KitgwQedX66VDfhr%2BRoo6Nbq1jPirYIetZVQHAoAhgdRZGJCXB9JsQHuSkYMC3K8cNOmLbwfYVLElA3YsAKqGIBoA2JHEkGZcSzkZEjSuc0cYJN8n0NAVMTNgWbPQmzEyp0UyeSlOiofdey66RnLeLAktgAOgc6qjTIVF6Vi614UijcI6gYzIhstJEzwlSkLY0TOAqQliCrj3T1WHUfMcHVoYB1ysS4gtisyyCcMNhz8XXGWSgRCy10slevARDaIy0cTfGUbolKogATuUk7DVutz2YNlxmZvKEk4QsIa8BCwzZhJ1wrJczqyCsxgXmjEKn5MolQA9PKhAxMgvq6JoQpO0AzYmPm2-ZAUDzc5oUBOHlBTVvyFVVCoxAjXMnvnN7amreCM38bhnpl6JlTWUnXHnxQF98BGTogLPOM87RM8B3KW0kglW4K5TWZwMM9tIjOBp9TKgxgcViV59pmB0J97lKeiwwIjGEfQ0-Bjky2nmkJeLVBaaLxWnuRFkFzPaeDhsU6zIhFhCTNI5L8amQ1aZCqaWkyTXO2NYM7tIxPOnmeRwuWSudhM2xt8m5g6C6d3E5tsuTEWWeX0xGRCbeNbO2D2e5OIw6OfJzDX-irEgBE5dAL4zQB%2BN-Hex6cyCgOOBN8SHJCFbSOjLClQmGZq-Gk6ic7PEzNC-FREy325QQWdcYCIU2aY1pPcEI%2BJpZuSdElgWqqUg2tulXinHwj6kPQESRwRN4QtgC0GiJhbJMgXzakIsfkC1TLdluZBTbceVPJkt920HkyUj8K7JLcySaJ2jiOYWy5ox0iF3vGWUxTUWapD5woeEMekMWYxpuEMj3gvMrdh%2BhF7UyRdOa6d2%2BJmPTEmm-DFzZOgLTsixcEv0h7EopjGWVNGRSsd4sUjqTZActnwORLDa3NGgeh0l2BmFD6N3GPw5U%2BLzFtEmmXnjew9ZHPNmNSZRNn5pLsfCRmYPks3YgAA)

**Comment by s24407-pj** [comment]
` "pnpm": {
    "overrides": {
      "svelte": "$svelte"
    }
},`

this + _pnpm i_ worked for me

**Comment by yookers** [comment]
Oh you're right, I guess it was due to `peerDependency` issues with Svelte after all. I didn't realize that it wouldn't work before with just adding the `pnpm override`. Now that I tried deleting `node_modules` and then doing a fresh install with `pnpm i`, it now works properly. Thanks for the fix. 😄
