### ISSUE TITLE
`createNewProject()` v1

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2349]
## Problem 

Apps can't create a project. 

## Proposal 

Expose a v1 of `createNewProject(path, { options })` in the inlang SDK. 

Until #1585 is implemented, we can create a new project with the inlang message format plugins as default, creating a folder in the inlang project to persist the messages. That unblocks @opral/inlang-fink and @opral/inlang-sherlock to start implementing onboarding flows. 

```
.
└── project.inlang
    ├── plugin.inlang.messageFormat/
    │   ├── de.json
    │   ├── en.json
    │   └── ... .json
    └── settings.json

```

```ts
const project = await createNewProject("blue_skydiver.inlang")

```

### Tasks

- [ ] validate that project ends with `*.inlang`
- [ ] pre-install common lint rules

## Additional information 

I propose to ship the most used lint rules by default. They can be uninstalled later

**Comment by samuelstroschein** [comment]
Duplicate in linear https://linear.app/opral/issue/MESDK-31/createnewproject-v1

**Comment by felixhaeberle** [comment]
@samuelstroschein why are we closing github issues which are connected to **not** done linear issues?
