### ISSUE TITLE
Broken link to the root of the website on SvelteKit

### ISSUE THREAD

**Issue by mquandalle** [opral/monorepo#2351]
### Problem

Links like  `<a href="/about">` are correctly translated to `<a href="/fr/a-propos">` on the French version.
But the link to the home page `<a href="/">` isn't converted to `<a href="/fr">` which is the root of the French version.

### Reproduction

- Setup paraglide on Sveltekit following https://inlang.com/m/dxnzrydw/library-inlang-paraglideJsAdapterSvelteKit#4-add-the-reroute-hook
- Create a "fr" lang in `project.inlang/settings.json`
- Create a `src/routes/about/+page.svelte` file
- Create links `<a href="/">` and `<a href="/about">`
- Observe that on the `/fr`, the about link is prefixed with the `/fr` path (`/fr/about`) but not the link to the home page (`/` instead of the expected `/fr`)

**Comment by mquandalle** [comment]
The issue was that the link to the home page `/` was directly in the root `+layout.svelte`, which isn't translated as explained in the documentation: 

>Help! Links in +layout.svelte aren't being translated
> As stated in the caveats, <a> tags are not translated if they are in the same component as the `<ParaglideJS>` component. Move your Links into a different component and it should work.

**Comment by LorisSigrist** [comment]
I was suspecting that too, I was trying to re-create this 😅.
We should probably log a warning if a Link is used in the same file as the `<ParaglideJS>` component

**Comment by mquandalle** [comment]
Yes sorry I didn't create a full clonable reproduction, I would have spotted the issue earlier.
