### ISSUE TITLE
Make Missing-Translation Lint rule less aggressive

### ISSUE THREAD

**Issue by LorisSigrist** [opral/monorepo#2352]
## Problem 
It's common that you may have two locales with mostly the same messages, but a few minor differences. Let's say `de-de` and `de-ch`. In that case, what you can do is to create a `de` base locale and only put the messages that are different into the sub-locales. 

However, currently the Missing-Translation lint rule will yell at you if you do this. 

## Proposal
Don't consider a message to be "missing", if it is present in a less-specific version of the language.

**Comment by felixhaeberle** [comment]
@LorisSigrist True, we need a global fallback mechanics for language tags which can be used by multiple packages.

**Comment by LorisSigrist** [comment]
Paraglide already does language-fallbacks when compiling, we could re-use that logic

**Comment by samuelstroschein** [comment]
closing as duplicate in favor of https://github.com/opral/monorepo/discussions/2191
