### ISSUE TITLE
[bug] @inlang/paraglide-js `1.2.9` has breaking missing dependency

### ISSUE THREAD

**Issue by iolyd** [opral/monorepo#2372]
### Problem

A project working just fine with a previous version of paraglide (`1.2.8`) breaks after upgrading to `latest` (`1.2.9`). See logs below:
```sh
node:internal/modules/esm/resolve:844
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@lix-js/fs' imported from /project/node_modules/.pnpm/@inlang+cross-sell-sherlock@0.0.2/node_modules/@inlang/cross-sell-sherlock/dist/recommendation/recommendation.js
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1131:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Expected behavior

Should work as previous version did, or if a peer dependency is required, should be documented in breaking changes somewhere.

### Reproduction

In a nextjs project:

- `pnpm up --latest`
- `pnpm dev`
- Observe thrown error in terminal

### Other information

- Node.js v21.6.2

**Comment by iolyd** [comment]
Also, on a tangent note about `cross-sell-sherlock`:

> Add New Recommendations: Automatically add new recommendations to the .vscode/extensions.json file if they are not already present.

Am I to understand that running Paraglide-js will lead to it automatically adding extension recommendations to my project?
It feels kind of pushy, doesn't it?

**Comment by LorisSigrist** [comment]
It will ask once if you want to use the vscode extension when you first run `paraglide-js init` since it greatly improves the dev-experience. 

Sorry for the broken build, I'll fix it right away

**Comment by LorisSigrist** [comment]
Fix is on it's way, CI is making problems
