### ISSUE TITLE
git proxy server running out of memory with badges

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#963]
## Problem

Opening large repositories in the editor like https://inlang.com/editor/github.com/NiklasBuchfink/jitsi-meet can lead to out-of-memory errors. 

> Jun 20 11:46:09 AM  FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

<img width="968" alt="CleanShot 2023-06-20 at 11 52 28@2x" src="https://github.com/inlang/inlang/assets/35429197/128a006e-1a4a-4121-bd40-765691950036">

## Reproduction 

- Unsure. Opening jisti-meet works for me but @NiklasBuchfink seemed to have triggered this bug by opening the repo. 
- But the logs in render.com can be checked https://dashboard.render.com/ (ignore "wrong inlang config setup failed")

## Additional information

This issue is likely part of removing the isomorphic git express middleware and having a dedicated `lisa/server`.

**Comment by NiklasBuchfink** [comment]
Request the following badge triggers this issue:
https://inlang.com/badge?url=github.com/NiklasBuchfink/jitsi-meet

**Comment by samuelstroschein** [comment]
> @NiklasBuchfink  Request the following badge triggers this issue:
https://inlang.com/badge?url=github.com/NiklasBuchfink/jitsi-meet

Oh, I see. In that case, here's whats likely happening: 

- _N_ Parallel requests for the large repository badge hit the server
- no badge is cached yet
- the server tries to clone _N_ times the large repository in parallel into memory to generate the badge
- _N_ > 5 comes down to 1.8GB of RAM + other tasks = exceeds memory.

This bug should be auto-fixed by lazy cloning of repos. The entire repo wouldn't get cloned into memory anymore massively speeding up the generation of badges, increasing cache hit chance, reducing memory consumption.

**Comment by samuelstroschein** [comment]
The future plan of project lisa foresees an unbundling of inlang.com and the git proxy server. A crash in a lisa server won't take down inlang.com anymore.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink @samuelstroschein Whats the status on this issue? Will @inlang/lix handle this? Who should be assinged?

**Comment by janfjohannes** [comment]
@felixhaeberle  this will be one of my immediate next tasks and i allready started looking into it, first step split up the systems, second step fix possible memory issues with proxy server

**Comment by felixhaeberle** [comment]
@janfjohannes one month later, status? 😄

**Comment by janfjohannes** [comment]
@felixhaeberle  the full fix for this is the lazy loading lix feature, martin shared a loom today with the current progress on this front. the planned timeline is attached, please note, that it will be probably be a week later or so as the editor changes and edge cases to work with the github happ/ oauth scope were a bit more fiddly than  in the project roadmap:


![Screenshot 2023-10-14 at 00 56 19](https://github.com/inlang/monorepo/assets/110794494/3b800af6-de69-4c6e-ab04-938f35aa93da)

**Comment by samuelstroschein** [comment]
closing as stale/likely a duplicate in linear
